### ISSUE TITLE
ICU Message Format

### ISSUE THREAD

**Issue by dbendy** [i18next/i18next#853] opened 2016-12-28 16:36 UTC
Has anyone ever used [ICU Message Format](http://userguide.icu-project.org/formatparse/messages) strings within `i18next`?  I am looking for a way to pass an ICU Message string into the `t` function provided by `i18next` and receive the proper output string, with the right variable replacement, pluralization, etc.  I am aware that `i18next` supports plurals, variable, and context, but it does so in its own format, whereas ICU Message is a community recognized standard for supporting this logic.  The translator that we work with uses ICU Message format so it would be very helpful to just feed these strings directly into `i18next`, without having to reformat them.  Alternatively, if you know of a library that will convert ICU Message strings to the `i18next` format, that would work as well.  Thanks!

**Comment by jamuhl** [comment] 2016-12-28 16:48
If your translator prefers ICU messageformat is irrelevant in my opinion - if i18next is your preferred solution (and there are reasons to choose it) your translator should get comfortable with the community recognized i18next format (phraseapp, webtranslateit and other support it).

Basically you might decide on thoughts like that:
- https://medium.com/@jamuhl/translate-my-website-please-732ddb622cba#.gh0hlaucc
- https://medium.com/@jamuhl/i18n-frameworks-the-unfair-showdown-8d436cd6f470#.ddjbb9nl8

Else would suggest to use formatjs or https://github.com/messageformat/messageformat.js - that uses ICU messageformat out of the box

Further you should look into http://locize.com - which even provides you with tooling for your localization process built on i18next.

**Comment by dbendy** [comment] 2016-12-28 16:59
Ok, thank you for the insight.  We are already using `i18next` and happy with it.  We are just exploring the pluralization feature and trying to make it work with our translator integration.  So, as far as you know, there are no libraries for converting ICU message format to `i18next` format?

If the format that `i18next` uses is communally recognized, is there a communally created document somewhere that describes it in detail, besides the `i18next` documentation?  This would be helpful for us.  If not, how does `i18next` ensure that they follow all the same rules as `phraseapp` and `webtranslateit`?

**Comment by jamuhl** [comment] 2016-12-28 21:31
no. sorry i do not yet know a tool for converting from icu to i18next.

the docs:
http://i18next.com/translate/
http://i18next.com/docs/plurals/

as plurals are defined by key suffix - the tooling does not have to care for it it's on the translator to define the additional needed keys.

http://locize.com our saas offering for localization does fully support correct plural generation.

**Comment by kachkaev** [comment] 2017-12-17 19:11
Hi @dbendy, I'm curious what you're using one year after your last comment here. I've been with `react-intl` for some time, but have started looking into i18next because of its awesome namespaces. However, the lack of ICU surprised me me a bit – that feels like a must-have feature. What are you using these days?

**Comment by jamuhl** [comment] 2017-12-18 07:46
ICU is "just" one format between others GNU gettext,...and while technically eventual most flexible not at all the best format for translators as it's technically bloated. Just my personal opinion. i18next json format was based on gettext but from there grown into it's own format - which nowadays is widely supported by translation platforms.

So no - i18next does not want to become just another ICU sugar - no need for that - even thought for some time about adding support which ended in if i do so i could also remove it from OSS -> there are tons of well crafted ICU i18n frameworks:

- https://formatjs.io/
- https://github.com/messageformat/messageformat.js
- https://github.com/format-message/format-message

Adding ICU format to i18next is rather simple:

- Add a postProcessor: https://www.i18next.com/misc/creating-own-plugins.html#post-processor doing the ICU formatting (going a step further you can even do a function cache for that)

**Comment by dbendy** [comment] 2017-12-19 16:57
@kachkaev: To answer your question, I was using `i18next` at the time that I had posted that question.  I was working for a different company and the time so I am technically not using it anymore, only because I am not there anymore.  However, they are still using it and I think pretty happy with it.  We found that the lack of ICU support wasn't really an issue until we wanted to support plurals.  The third party translator that we were working with was willing to support different formats for us but once we requested support for plurals in the structure that `i18next` expects, they suggested moving over to using ICU in stead.  There was no further progress on that project but I imagine that we would have stuck with `i18next` and just adopted a preprocessor, as @jamuhl suggests.

**Comment by karellm** [comment] 2018-03-24 13:47
@jamuhl I've been using `i18next` for all my i18n projects (I'm behind `i18next-parser`). I also happen to use Ember which is currently having conversations about standardizing i18n for the community. The preferred solution at the moment uses ICU. I was wondering, beside the "technically bloated", why do you think ICU compared to the format of `i18next`. This is not a request for you to add the feature, just a personal curiosity for your experience.

**Comment by jamuhl** [comment] 2018-03-24 16:42
@karellm hi...yes...i18next-parser i know ;)

Will i see the technical adaption growing on ICU i do not see it being adapted in the translation industry (might be a javascript thing - but there are still other formats powering more big projects and line of business apps powered by .net, ... => gettest, resfiles, android strings). So honestly it's just another format between others and not the easiest to be handled by translators.

Not sure if you already tried out https://locize.com - we support i18n.js and ICU format beside i18next json format there - for ICU even syntax highlighting, validation and plural conversion between languages. So really nothing against ICU.

I more than once thought about making the "translator" inside i18next replaceable by some ICU parser...wouldn't be to hard i guess. Just i'm not sure it makes a lot of sense as there are enough ICU i18n frameworks in the wild - what would be the benefit of i18next? The plugins for loading, language detection, ...?!? Being able to use it on most UI frameworks...?!??

Really open for discussion...

**Comment by karellm** [comment] 2018-03-24 17:10
I haven't tried locize yet but I mean to soon. 

Regarding the value for i18next, I don't know really. I like that ICU has a single identifier rather than multiple key/value for context/plural but I find the ICU syntax quite bloated indeed. I guess that's a trade off that doesn't really matter in the end, especially if there is an interface like Locize involved on the translator's end.

**Comment by kachkaev** [comment] 2018-04-12 15:38
@karellm same for me regarding a single identifier in pluralized strings. In some languages such as Russian there are several forms of plurals depending on the count; seeing all these strings in one place is quite useful.

Another really great ICU feature is support for multiple counts in one string, e.g. `There are 20 eggs in 2 baskets`. Without ICU, this string has to have 2×2 = 4 keys in an English i18n file, or 2×3 = 6 keys in a Russian translation. Changing the string to `There are 15 boiled and 5 raw eggs in 2 baskets` would require adding 2 or more keys to a non-ICU localization file while with ICU it's just a matter of making a minor amendment to an already existing translation.

Here's an example of pluralization in one project where I use react-intl and ICU:
[gitlab.com/kachkaev/website-frontend → lang/ru.json#L23-24](https://gitlab.com/kachkaev/website-frontend/blob/e8dab3f18ceebe978c40aa546c61912725bde692/lang/ru.json#L23-24)
It says `X repo(s) in Y language(s)`. Yes, the string is longer than a few separately keyed chunks, but as a translator I can read and edit the text without issues.

ICU also makes it easy to deal with Yoda-like translations like `2 baskets with 20 eggs there are` (this may sound better than the original phrase in some language). To achieve this such a shuffling, a translator simply moves the words in a single string according to their best judgement, but in non-ICU ‘chunked’ translation strings a trick like that becomes a nightmare. Moving a part of a string (e.g. `there are`) to the end of a phrase may even require the developers's input, which is pretty bad efficiency-wise.

@jamuhl it'd be great if ICU became the first-class citizen in `i18next` – that will be such a help in many situations! 🚀

**Comment by jamuhl** [comment] 2018-04-12 15:44
@kachkaev we might add an extension that exchanges the translation logic from i18next to icu. Think that's not a big deal...just you can't switch between them dynamically...either all ICU or all i18next.

Would be something like `i18next.use(ICU);`

**Comment by kachkaev** [comment] 2018-04-12 15:45
@jamuhl that would be amazing! I'll be happy to test your implementation in my [`website-frontend`](https://gitlab.com/kachkaev/website-frontend/) project – simply ping me when you need this!

**Comment by jamuhl** [comment] 2018-04-13 09:28
@kachkaev ok this is highly experimental and i did only some basic testing with it:

using:
i18next@11.2.2

and:
i18next-icu@0.1.0

https://github.com/i18next/i18next-icu

if this turns out to be of value i might even consider adding some polyglot, i18n-js support ;)

**Comment by kachkaev** [comment] 2018-04-13 09:34
Many thanks @jamuhl – i’ll try to test it within a few days!

**Comment by kachkaev** [comment] 2018-04-13 09:35
shall we keep this issue opened for now?

**Comment by kachkaev** [comment] 2018-04-13 10:17
Yeah, that's true. Namespaces, language detection and fallback, updating translations with incomplete strings and other cool things is what attracted me in `i18next` despite my prior experience with `react-intl` and ICU. To be honest, I recently used `react-i18next` in a couple of new projects despite the pain points I described before. But with ICU finally working together with `i18next`your library is a clear winner to `react-intl` for me!

I'm so keen to play with `i18next`+`ICU` now that I fear that my current work is at risk 😆  But I'll try to stay strong and finish it first 😅

**Comment by jamuhl** [comment] 2018-04-13 10:56
with react-i18next@7.6.0 i added tOptions to the Trans component so you can do: https://github.com/i18next/react-i18next/blob/master/example/react_icu_withHOC/src/App.js#L29

with translation: https://github.com/i18next/react-i18next/blob/master/example/react_icu_withHOC/public/locales/en/translations.json#L8

you get:
<img width="715" alt="screen shot 2018-04-13 at 12 53 56" src="https://user-images.githubusercontent.com/977772/38731320-1a5b8c1a-3f1a-11e8-980f-db6bc5f5df58.png">

**Comment by kachkaev** [comment] 2018-04-17 09:24
Again many thanks for implementing ICU @jamuhl! Here's an update on my ongoing `react-intl` → `react-i18next` transition experiment.

Given the ICU support, I like `react-i18next` so much more than `react-intl`! The way it can deal with the namespaces and missing translations is awesome and I'm also a big fan of `<1></1>` syntax in `<Trans />`! This syntax has simplified my translation files even further, because I don't have to use different translation keys for strings inside the links or emphases within a paragraph and the messages become much easier to read!

At the moment, there seems to be one blocking issue and one minor one.

The blocking issue is a problem with [plural categories](https://formatjs.io/guides/message-syntax/#plural-format). For some reason, the following ICU message does not work in `react-i18next`:

```
We invited <1>{numPersons, number} {numPersons, plural, one {person} many {persons}}</1>
```

```
Cannot read property 'length' of undefined
```
<details>
<summary>stack trace</summary>
<pre>
TypeError: Cannot read property 'length' of undefined
    at MessageFormat._format (/src/core.js:192:31)
    at MessageFormat._format (/src/core.js:216:28)
    at MessageFormat.format (/src/core.js:45:30)
    at ICU.parse (/Users/ak/-/projects/kachkaev/website/frontend/node_modules/i18next-icu/dist/commonjs/index.js:56:17)
    at Translator.extendTranslation (/Users/ak/-/projects/kachkaev/website/frontend/node_modules/i18next/dist/commonjs/Translator.js:233:29)
    at Translator.translate (/Users/ak/-/projects/kachkaev/website/frontend/node_modules/i18next/dist/commonjs/Translator.js:216:18)
    at I18n.t (/Users/ak/-/projects/kachkaev/website/frontend/node_modules/i18next/dist/commonjs/i18next.js:338:73)
    at fixedT (/Users/ak/-/projects/kachkaev/website/frontend/node_modules/i18next/dist/commonjs/i18next.js:324:21)
    at Trans.render (/Users/ak/-/projects/kachkaev/website/frontend/node_modules/react-i18next/dist/commonjs/Trans.js:155:31)
    at processChild (/Users/ak/-/projects/kachkaev/website/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:2195:18)
    at resolve (/Users/ak/-/projects/kachkaev/website/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:2052:5)
    at ReactDOMServerRenderer.render (/Users/ak/-/projects/kachkaev/website/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:2337:22)
    at ReactDOMServerRenderer.read (/Users/ak/-/projects/kachkaev/website/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:2311:19)
    at renderToString (/Users/ak/-/projects/kachkaev/website/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:2683:25)
    at renderPage (/Users/ak/-/projects/kachkaev/website/frontend/node_modules/next/dist/server/render.js:180:26)
    at Function.getInitialProps (/Users/ak/-/projects/kachkaev/website/frontend/.next/dist/bundles/pages/_document.js:294:47)
</pre>
</details>

Replacing `many` with other `works` though:

```
We invited <1>{numPersons, number} {numPersons, plural, one {person} other {persons}}</1>
We invited <1>{numPersons, plural, =0 {no persons} =1 {one person} other {# persons}}</1>
```

Looks like having `other` is essential at the moment, which was not the case with `react-intl`.

I guess for a similar reason I'm getting different pluralisation results for Russian on the sever and in the client. Check out this initial flickering on the page:

![i18n-few-other](https://user-images.githubusercontent.com/608862/38860279-c343b43c-4227-11e8-8ad7-dcbc6f10fbb0.gif)

The server correctly chooses between `one`, `few` and `other` (aka `many`) on the server, but never picks `few` on the client, which makes updated translations grammatically incorrect. Should the ICU plugin configure anything in addition to avoid this? I don't remember making any special API calls with `react-intl` to achieve this, but I remember they were using [formatjs](https://formatjs.io/) under the hood.

The support of plural categories is critical, because in many languages `=1` & `other` is not enough. Check out the [categories for Russian, for example](https://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#ru) – they are insane!

---

The minor issue is that `tOptions` prop is not a part of `Trans` component as far as `@types/react-i18next` knows. This causes a TypeScript error and thus fails the build:

```
[ts] Property 'tOptions' does not exist on type 'IntrinsicAttributes
& IntrinsicClassAttributes<Trans> & Readonly<{ children?: ReactNode; }> & Rea...'.
```

<img width="391" alt="screen shot 2018-04-16 at 22 13 34" src="https://user-images.githubusercontent.com/608862/38835579-85b840c4-41c3-11e8-8465-65e9b425040c.png">


You can check my ongoing transition process here:
https://gitlab.com/kachkaev/website-frontend/merge_requests/3/diffs

**Comment by jamuhl** [comment] 2018-04-17 11:38
@kachkaev hm...rather strange...i18next-icu uses intl-messageformat - so same as react-intl basically.

The problem is intl-message format on node.js (https://github.com/yahoo/intl-messageformat/blob/master/index.js#L9) requires all plural rules while in browser you will have to pull in additional scripts which adds them to some global https://github.com/yahoo/intl-messageformat/blob/master/dist/locale-data/ar.js

react-intl even rebundle those with a shim form intl. At least it seems like that: https://unpkg.com/react-intl@2.4.0/locale-data/

Bundling all those rules would result in a to big module...letting those being added in userland seems not userfriendly to me.

Might go and remove that yahoo stuff in favour to: https://github.com/format-message/format-message/tree/master/packages/format-message-interpret at least there are all plural rules bundled in a size friendly way.

So any feedback would be welcome on this as i never used react-intl myself and not sure how bundling those plural files works there...

regarding 2) typescript...i do not support those files myself...might take a while for those getting updated.

**Comment by jamuhl** [comment] 2018-04-17 12:24
Give me a few seconds...i currently work on making it as react-intl does it: https://github.com/yahoo/react-intl/wiki#locale-data-in-browsers

From that version we could further see how to improve that -> PR welcome

thanks for taking care for the typescript issue...

**Comment by jamuhl** [comment] 2018-04-17 12:34
i18next-icu@0.2.0 -> https://github.com/i18next/i18next-icu#plural-support

**Comment by kachkaev** [comment] 2018-04-17 12:56
Awesome, many thanks for the update!

I'm not sure why, but I'm getting this exception on the client:

```
i18n.ts?3d47:39 Uncaught TypeError: Cannot read property 'addLocaleData' of undefined
    at i18n.ts?3d47:39
    at i18next.js?9518:144
    at done (i18next.js?9518:245)
    at i18next.js?9518:260
    at Connector.load (BackendConnector.js?2fbf:182)
    at I18n.loadResources (i18next.js?9518:194)
    at setLng (i18next.js?9518:259)
    at I18n.changeLanguage (i18next.js?9518:269)
    at load (i18next.js?9518:139)
```
Here is what I did:
https://gitlab.com/kachkaev/website-frontend/merge_requests/3/diffs?commit_id=a042519486fe02884a45f55c1256d6fdadbcdf67

Also tried the following, but the same error showed up:

```ts
if (!i18nInstance.isInitialized) {
  i18nInstance.init(options);
}
(i18nInstance as any).ICU.addLocaleData(en);
(i18nInstance as any).ICU.addLocaleData(ru);
```

Not casting `i18nInstance` to `any` produces `[ts] Property 'ICU' does not exist on type 'i18n'.`, which is a TypeScript-specific thing.

**Comment by kachkaev** [comment] 2018-04-17 13:13
> i see...i18next.ICU is only set after init...hm...

I also thought so, but this did now work: https://gitlab.com/kachkaev/website-frontend/merge_requests/3/diffs?commit_id=a042519486fe02884a45f55c1256d6fdadbcdf67#94b755d1090dafeaa0244addd61f16720798c9e4_37_38

Will try `const icu = new ICU();` now.

> i could add an option to add those in init settings:

How would client-side webpack load stuff from these lines?

```
import en from "i18next-icu/locale-data/en";
import ru from "i18next-icu/locale-data/ru";
```

**Comment by jamuhl** [comment] 2018-04-17 13:16
i18next-icu@0.3.0 --> https://github.com/i18next/i18next-icu#plural-support

```js
import i18next from 'i18next';
import ICU from 'i18next-icu';

import fr from 'i18next-icu/locale-data/fr';

i18next
  .use(ICU)
  .init({
    i18nFormat: {
      localeData: fr // you also can pass in array of localeData
    }
  });
```

**Comment by kachkaev** [comment] 2018-04-17 13:18
This worked for me: https://gitlab.com/kachkaev/website-frontend/merge_requests/3/diffs?commit_id=00c289408853da6a50920ab7e371ae7f587cae79 :tada:

Will upgrade to 0.3.0 and make the solution even smaller! `react-i18next` is soooo awesome now!

**Comment by kachkaev** [comment] 2018-04-17 13:31
Hmm... `i18nFormat: { localeData: [en, ru] }` did now work for me for some reason (see [commit](https://gitlab.com/kachkaev/website-frontend/merge_requests/3/diffs?commit_id=a41cbdd034f0f78229699d7c75d06bcc50a941e2)). The interface flickers again in Russian as [previously](https://github.com/i18next/i18next/issues/853#issuecomment-381918140). [Switching back](https://gitlab.com/kachkaev/website-frontend/merge_requests/3/diffs?commit_id=58a39297aff8ed5d80302b30c83f01c627fab2e6) to `new ICU()` approach fixed everything.

**Comment by jamuhl** [comment] 2018-04-17 13:44
hm...should be the same...but no time right now to investigate deeper why not...hopefully after holidays i get more time to check this.

**Comment by kachkaev** [comment] 2018-04-17 13:46
Thank you. What you've already done is a breakthrough!

**Comment by jamuhl** [comment] 2018-04-17 13:55
hm...i guess i now why it does not work.

SSR -> initResourceStore --> wait gets set to false --> init might not be finished while translation already works based on all needed passed in -> just not being initialized also means not yet added that locale-data for intl (while adding it on the `new ICU()` will be done immediatly.

Will need to think more about possible solution to this...but not right now ;)

**Comment by kachkaev** [comment] 2018-04-18 08:00
I deployed to production from the [`i18next` branch](https://gitlab.com/kachkaev/website-frontend/merge_requests/3/diffs) and all worked pretty well! There was just one minor glitch in the dockerized version of my Next.js app – it was the same as with `react-intl` previously.

When a page was loaded in Russian, number `1180` was first formatted as `1,180` on the server and then quickly changed to `1 180` by the client (which is correct for Russian). Because the behaviour was the same for `react-lintl` and `react-i18next`, I guessed the issue was to do with Node.js itself and first tried to [upgrade](https://gitlab.com/kachkaev/website-frontend/commit/248d6cfc948c07733cb8d089d6413439e7c188c0) `node:8.9.4-alpine` to `node:9.11.1-alpine`. However, the glitch did not disappear.

After a bit of searching, I discovered that the official [Node.js docker image](https://hub.docker.com/_/node/) (at least alpine-based) does not have ICU preinstalled. The [solution](https://gitlab.com/kachkaev/website-frontend/commit/8868c0b616e3e6febd1a0d53ba7827f40e2a2c3b) was to `yarn add full-icu` locally and then add `ENV NODE_ICU_DATA=/usr/src/app/node_modules/full-icu` to the Dockerfile. This helped Node inside Docker find the ICU rules and thus format the number correctly. No more flickering between `1,180` and `1 180` on page load!

Alternatively, I could just `yarn add full-icu` inside Docker because this module is not needed on the development machine and is useless without setting `NODE_ICU_DATA`. However, I still preferred to keep it in `package.json` and `yarn.lock` for a better version stability.

Although this info is not directly related to `i18next`, I hope it can help someone one day.

Now everything is ideal and I'm really looking forward to use `i18next` in all my future projects (perhaps, in conjunction with [locize.com](https://locize.com/) one day)! 😉

**Comment by jamuhl** [comment] 2018-04-18 08:10
@kachkaev good to know about the docker image "issue"...hope i will remind that when needed.

But overall sounds like we're getting there...wasn't to sure i like this step of enabling ICU format...but seems not to bad overall. i18next adds enough value i guess to be picked over pure react-intl (which was my biggest concern...why would one use icu on i18next and not directly react-intl).

**Comment by jamuhl** [comment] 2018-04-18 08:12
@kachkaev would be awesome if you could do some medium post in future about your migration from react-intl to react-i18next + icu -> guess that would help a lot of developers making their mind about react-intl vs. react-i18next.

**Comment by jamuhl** [comment] 2018-04-18 08:27
not sure but i guess react-intl still has some issues with the yahoo story.

Yes will check and eventual do a post - but guess yours would be better as you did a real migration. Will see ;)

Thanks...yes will take some time to relax and fill my batteries...

**Comment by kachkaev** [comment] 2018-04-18 11:11
A PR to add tOptions prop to `<Trans />` (relates to TypeScript users only):
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25089

**Comment by jamuhl** [comment] 2018-04-18 15:48
closing this again...

**Closed by jamuhl** 2018-04-18 15:48 UTC
