### ISSUE TITLE
Which IE versions does this plugin support?

### ISSUE THREAD

**Issue by aonzzung** [i18next/i18next#553] opened 2016-02-12 10:08 UTC
Hi,

I've tried and it's not working with IE8 (I know it's old and not support by Microsoft anymore).
Anyways, I'd like to know exactly which versions of IE this plugin can support.

What is the lowest IE version it's compatible with ?

Thanks

**Comment by jamuhl** [comment] 2016-02-12 15:41
can only guess but i think it should run on ie9. but having some sims in place for old browsers should make it run on ie8.

**Comment by aonzzung** [comment] 2016-02-15 08:10
Thanks @jamuhl for your info.

**Just FYI** : I've tried once and it breaks on ie8

Thanks

**Comment by jamuhl** [comment] 2016-02-15 08:18
ie8 was dropped on v2.

works on ie10 and up.

**Comment by aonzzung** [comment] 2016-02-15 08:25
Thanks for your confirmation @jamuhl

**Comment by emileber** [comment] 2016-03-09 20:01
I'm trying to use i18next with at least IE9 and up. I used es5-shim but without success, IE10 and down are still failing. I'm getting the following error:

> Unable to get property « added » of undefined or null reference

Which comes down to line 221:

```
_this.observers[event] = _this.observers[event] || [];
```

Where `_this` refers to a different object on IE10 and down than on IE11 or chrome. On IE10, it seems to be a reference to the i18next object. On chrome and IE11, it is one of `ResourceStore`, `Connector`, `Translator` object.

While reading the doc, I saw the following:

> time to let them go - use shims when needed.

Which shims are needed exactly? (in addition to es5-shim and es6-shim, which seems to not be enough?)

**Comment by jamuhl** [comment] 2016-03-10 09:32
@emileber seems not related to shim...rather confused why IE10 holds wrong reference:

https://github.com/i18next/i18next/blob/master/i18next.js#L221

**Comment by emileber** [comment] 2016-03-10 13:43
here's the minimal exemple to reproduce the bug in IE10 and below.

https://jsfiddle.net/q0joy7qw/2/

**Comment by jamuhl** [comment] 2016-03-10 16:47
ok...this one goes down to change from babel5 to babel6: https://github.com/babel/babelify/issues/133

babel6 does not support IE < 10 - but seems there are workarounds to get this up again.

could you try adding this polyfill:
https://gist.github.com/edoardocavazza/47246856759f2273e48b#file-object-setprototypeof-ie9-js

?!?

**Comment by jamuhl** [comment] 2016-03-11 09:30
ok...think i got it:

https://jsfiddle.net/c7k51vcw/6/ //-> the es5 shim is only needed for ie9 (obviously)

i18next v2.3.4

**Comment by jamuhl** [comment] 2016-03-12 15:07
@emileber can you confirm latest version works?

**Comment by emileber** [comment] 2016-03-13 19:23
Thank you very much for your fast response time and sorry for my late answer, I did see your comment but did not had time to test it yet. I will probably check if it works later today.

**Comment by emileber** [comment] 2016-03-14 03:04
Yeah, the fiddle works with IE10 and IE9.

**Comment by jamuhl** [comment] 2016-03-14 07:44
perfect...thank you for the verification...

**Comment by jamuhl** [comment] 2016-03-23 07:16
closing for now...seems situation is more clear now (plus hints for correct shim in docs)...thanks to all for the help on this.

**Closed by jamuhl** 2016-03-23 07:16 UTC
