### ISSUE TITLE
i18next.cloneInstance() should behave exactly like the i18next.init() but with new options.

### ISSUE THREAD

**Issue by KostyaTretyak** [i18next/i18next#1819] opened 2022-08-16 18:51 UTC
## 🚀 Feature Proposal

`i18next.cloneInstance()` should behave exactly like the `i18next.init()` but with new options.

## Motivation and example

For now, during `i18next.cloneInstance({ debug: true })` call there is no debug output. But why? Internally, this method calls [i18next.init()](https://github.com/i18next/i18next/blob/9304a251e54d58cda88fb484299bef67f2025c2e/src/i18next.js#L591), so why shouldn't this method behave the same as `i18next.init()`?

I will tell more details how I want to use i18next. I want to make a centralized instance of i18next, then make clones of that instance for each module (in my NodeJS framework), and then use the `t()` function for individual requests with individual language settings or namespaces.

Each module must have its own translation files:

```text
├── modulename
│   ├── ...
│   └── locales
│       ├── current
│       │   ├── en
│       │   └── uk
│       └── imported
│           ├── one
│           │   ├── en
│           │   └── uk
│           └── two
│               ├── en
│               └── uk
```

Where `one` and `two` are directories with translation files for imported modules.

When I call `i18next.cloneInstance(options)`, I expected that my `options` will be merged with `options` passed during  `i18next.init(options)`. So if in the new options I specify, for example, the path to the new translation files, `i18next.cloneInstance(options)` should reload those files for the new instance. Isn't that logical?

**Comment by adrai** [comment] 2022-08-16 19:11
the options are merged, but the problem is the debug flag is ignored, because it is used in the "global" logger

**Comment by KostyaTretyak** [comment] 2022-08-16 19:14
I hope this can be easily fixed.

**Comment by adrai** [comment] 2022-08-16 19:19
this is by design

**Comment by KostyaTretyak** [comment] 2022-08-16 19:20
Any reason why?

**Comment by adrai** [comment] 2022-08-16 19:30
maybe @jamuhl can explain this

**Comment by adrai** [comment] 2022-08-16 19:31
fyi: I've just created a PR that would create also a logger clone: #1820

**Comment by KostyaTretyak** [comment] 2022-08-16 19:36
Ok, how about:

> So if in the new options I specify, for example, the path to the new translation files, `i18nex.cloneInstance(options)` should reload those files for the new instance. Isn't that logical?

Perhaps it will be more difficult, but is it possible to do it?

**Comment by adrai** [comment] 2022-08-16 19:41
This would be a major change... and is for sure not part of the current cloneInstance "contract".
cloneInstance shares store, plugins and initial configuration...

I suspect for your use case you better use createInstance and handle each instance on its own: https://www.i18next.com/overview/api#createinstance

**Comment by KostyaTretyak** [comment] 2022-08-16 20:03
> cloneInstance shares store, plugins and initial configuration...

I think in major version of i18next `cloneInstance()` should renamed to `shareInstanceWithOptions()`.

**Comment by jamuhl** [comment] 2022-08-17 04:52
`cloneInstance` creates a copy of the main instance -> and the only real use case I'm aware of is using it on serverside (node.js, ...) in szenarios where multiple requests from different users with different languages are handled async and you need i18next set to a language per user/request.

So, I understand your proposal...but I don't see the need as cloneInstance does not need to be the same as i18next.init -> as it's a clone not a `createInstance`

**Closed** 2022-08-17 09:50 UTC
