### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by bildungsroman** [i18next/i18next#1921] opened 2023-03-07 23:16 UTC
## 🐛 Bug Report

I'm getting the error `Type instantiation is excessively deep and possibly infinite` when defining `CustomTypeOptions`. 

My type definition:

```js
// i18next.d.ts
import resources from "../i18n/locales/resources";

declare module "i18next" {
	interface CustomTypeOptions {
		returnNull: false;
		resources: typeof resources['en'];
	}
}
```

where `resources` are:
```js
// i18n/locales/resources
import definitions_de from './definitions/de.json';
import definitions_en from './definitions/en.json';
import errors_de from './errors/de.json';
import errors_en from './errors/en.json';

export const resources = {
	de: {
		definitions: definitions_de,
		errors: errors_de,
	},
	en: {
		definitions: definitions_en,
		errors: errors_en,
	},
<etc.>
}
```

In my code, I'm doing:

```js
// src/myCode
const t = i18nInstance.getFixedT(this.locale as Locale);

throw new Error(t('index.edgeError'));
```

## Expected behavior

I would expect the type definition to work. And the code to compile. However, while I don't get any tslint errors, my tests are failing with the error `Type instantiation is excessively deep and possibly infinite`, which also shows up (sometimes) in VS Code.

## Your Environment

- *runtime version*: node16
- *i18next version*: "^22.4.10", "typescript": "^4.9.5",
- *os*: Mac

**Comment by sedge** [comment] 2023-03-08 01:14
I'm seeing something very similar 👀

**Comment by adrai** [comment] 2023-03-08 06:19
https://github.com/i18next/react-i18next/issues/1601
https://github.com/i18next/react-i18next/issues/1600
https://github.com/i18next/i18next/pull/1911

**Comment by adrai** [comment] 2023-06-15 09:44
Please try with i18next v23.0.1 and react-i18next v13.0.0

**Comment by tsuyoyo** [comment] 2023-06-29 01:00
FYI: In our case, we needed `react-i18next v13.0.1` (not `v13.0.0`) to resolve `Type instantiation is excessively deep and possibly infinite` warning.

https://github.com/i18next/react-i18next/issues/1601#issuecomment-1602029316

**Comment by yeliex** [comment] 2023-06-29 09:32
the problem still exist with `i18next@23.2.5` and `react-i18next@13.0.1` when there are many namespaces(currently about 20 and would be 100+ in thre future)

**Comment by adrai** [comment] 2023-06-29 14:12
@yeliex an example repository may help @pedrodurek to investigate

**Comment by esetnik** [comment] 2023-06-30 04:42
@adrai @pedrodurek please see https://github.com/esetnik/react-i18next/tree/repro-%231921.

Steps to reproduce:
1. checkout repro branch
2. npm install
3.

```bash
❯ npm run build

> simple-multi-namespaces@1.0.0 build
> react-scripts build

Creating an optimized production build...
Failed to compile.

TS2589: Type instantiation is excessively deep and possibly infinite.
    18 |   const { t } = useTranslation();
    19 |
  > 20 |   return <div>{prop ?? `${t('labels.complete')}`}</div>;
       |                           ^^^^^^^^^^^^^^^^^^^^
    21 | };
    22 |
    23 |
```

**Comment by esetnik** [comment] 2023-07-11 12:45
@adrai are there any updates to share here?

**Comment by pedrodurek** [comment] 2023-07-11 23:48
Hey @esetnik, the problem lies in the `resources` type. You're importing the default module (i18n) and naming it `resources`, not the actual `resources` which is being exported as a named module. This should fix your problem:
```tsx
// index.d.ts
import { resources } from '../i18n';
import { defaultNS } from '../i18n';

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: typeof defaultNS;
    resources: typeof resources['en'];
  }
}

```

**Comment by esetnik** [comment] 2023-07-12 16:07
@pedrodurek I made the change you suggested and the previous reproduction I reported is now working correctly. However in my own project I can't seem to make it work without facing the eslint issue mentioned in #1883. I had erroneously believed that the two issues were related.

**Comment by adrai** [comment] 2023-07-26 05:44
Can you try if it's better with v23.3.0?

**Comment by esetnik** [comment] 2023-07-26 20:03
I can't reproduce this so i'm not sure if there's any improvement in v23.3.0

**Comment by adrai** [comment] 2023-07-26 20:05
@bildungsroman we're closing this issue. If you think that's still an issue you can reopen it and provide an updated reproducible example.

**Closed** 2023-07-26 20:05 UTC
Labels: typescript
