### ISSUE TITLE
Type issues with TypeScript 4.x

### ISSUE THREAD

**Issue by mscharley** [i18next/i18next#2008] opened 2023-07-31 05:44 UTC
## 🐛 Bug Report

The new i18next types introduced with 23.4.0 don't work with TypeScript 4.x.

There seem to be a number of issues:

1. `export type * from "some/path"` is only available in TypeScript 5.x.
2. The import paths shouldn't include the `d.ts` suffix.
3. When imported via ESM, the types need the `.js` suffix.
4. TypeScript doesn't honour `typesVersions` when resolving types via the `exports` section of the package.json.
5. You can't redirect individual files using `typesVersions`:

    > Note that redirections only affect the external API of a package; import resolution within a project is not affected by typesVersions. For example, a d.ts file in the previous example containing import * as foo from "./index" will still map to index.d.ts, not index.v3.d.ts, whereas another package importing import * as foo from "package-name" will get index.v3.d.ts.
    > -- https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#file-redirects

It might be simpler to just downgrade to the looser v4 types, or drop the v4 types entirely. I tried messing with this for a while to try to submit a patch, but I couldn't get everything working in all cases. Unfortunately we're still stuck on v4 because of incompatibilities with other libraries.

## Your Environment

- *runtime version*: node v16
- *i18next version*: 23.4.1
- *os*: Mac
- *typescript*: 4.9.5

**Comment by SebastianHueftlein** [comment] 2023-07-31 12:53
For me previously working type imports like
```
import { TOptions } from 'i18next';
```

are now also throwing the error
> error TS2614: Module '"i18next"' has no exported member 'TOptions'. Did you mean to use 'import TOptions from "i18next"' instead?

after the https://github.com/i18next/i18next/pull/2007 change.

Using `"typescript": "4.9.5"`

**Comment by Shurna83** [comment] 2023-08-02 10:06
I am facing this issue as well, but with TFunction type. I am also using Typescript 4.9.5.

> For me previously working type imports like
> 
> ```
> import { TOptions } from 'i18next';
> ```
> 
> are now also throwing the error
> 
> > error TS2614: Module '"i18next"' has no exported member 'TOptions'. Did you mean to use 'import TOptions from "i18next"' instead?
> 
> after the #2007 change.
> 
> Using `"typescript": "4.9.5"`

**Comment by mscharley** [comment] 2023-08-08 04:05
Hmm. Having looked at the merge history, I'm not sure why but `i18next@23.4.2` is working for us now.

**Comment by exhilaratedguy** [comment] 2023-09-07 14:25
Any updates on this?

**Comment by mscharley** [comment] 2023-09-17 07:48
@pedrodurek any updates? Stale bot has kicked in but as far as I'm aware after checking the changelog, this is still active. I can't directly check though because my project has moved on to TypeScript 5 which avoided this issue.

**Comment by ZotyoNegentropics** [comment] 2023-09-18 11:37
> @pedrodurek any updates? Stale bot has kicked in but as far as I'm aware after checking the changelog, this is still active. I can't directly check though because my project has moved on to TypeScript 5 which avoided this issue.

I can confirm this is still a problem with 4.x typescript.
We had to freez the i18next version to 23.3.o in our projects

**Comment by pedrodurek** [comment] 2023-11-10 16:11
@drewbrend I'll investigate it today

**Comment by Shurna83** [comment] 2023-11-13 09:23
According to [> this commit <](https://github.com/i18next/i18next/commit/a3d76377d931876077529e4222b96ab2c6742b2a) I understand that TypeScript <5 is not officially supported anymore. Is my understanding correct or not?

**Comment by mscharley** [comment] 2023-11-16 09:27
If there is interest in still supporting TypeScript 4.x, I've learned a lot about this in the last 5 months. I use d.ts rollups via [`api-extractor`](https://www.npmjs.com/package/@microsoft/api-extractor) to work around differences in imports between CommonJS and ESM by removing relative imports entirely and I've found that while `typesVersions` isn't supported for exports, there is a separate spec for doing different types for exports, [example here.](https://github.com/mscharley/dot/blob/dc0ed1c9d6a8f452d11113d9fd42d1b88a9361db/package.json#L20-L43) You still need a `.d.cts` and `.d.ts` because TypeScript itself insists that the types be different between `import` and `require` and match the naming scheme that is relevant for how you have your project setup, but the files can have the same contents.

**Comment by adrai** [comment] 2023-11-28 08:26
Please check with the newest versions... TS v5 is preferred, but TS 4.x should still work

**Comment by drewbrend** [comment] 2023-11-28 12:54
> Please check with the newest versions... TS v5 is preferred, but TS 4.x should still work

WIth v23.7.7 I'm still getting errors like this from within `i18next`:

> ../../node_modules/i18next/index.v4.d.ts(2,34): error TS2691: An import path cannot end with a '.d.ts' extension. Consider importing './typescript/helpers.js' instead.

**Comment by adrai** [comment] 2023-11-28 12:59
> > Please check with the newest versions... TS v5 is preferred, but TS 4.x should still work
> 
> With TSv4.9.5 and i18next v23.7.7 I'm still getting errors like this from within `i18next`:
> 
> > ../../node_modules/i18next/index.v4.d.ts(2,34): error TS2691: An import path cannot end with a '.d.ts' extension. Consider importing './typescript/helpers.js' instead.

@drewbrend that's not possible the index.v4.d.ts file does not exist in the new i18next version, btw: its v23.7.6 not v23.7.7... make sure you've installed it and if the problem still persist, please provide a minimal reproducible example repository.

**Comment by drewbrend** [comment] 2023-11-28 13:29
> > > Please check with the newest versions... TS v5 is preferred, but TS 4.x should still work
> > 
> > 
> > With TSv4.9.5 and i18next v23.7.7 I'm still getting errors like this from within `i18next`:
> > > ../../node_modules/i18next/index.v4.d.ts(2,34): error TS2691: An import path cannot end with a '.d.ts' extension. Consider importing './typescript/helpers.js' instead.
> 
> @drewbrend that's not possible the index.v4.d.ts file does not exist in the new i18next version, btw: its v23.7.6 not v23.7.7... make sure you've installed it and if the problem still persist, please provide a minimal reproducible example repository.

My mistake, v23.7.7 was a typo.

As far as I can tell, `index.v4.d.ts` does exists, check out this output from npm pack:

```
... % npm pack i18next
npm notice 
npm notice 📦  i18next@23.7.6
npm notice === Tarball Contents === 
npm notice 1.1kB  LICENSE                    
npm notice 3.7kB  README.md                  
npm notice 85.4kB dist/cjs/i18next.js        
npm notice 86.1kB dist/esm/i18next.bundled.js
npm notice 86.1kB dist/esm/i18next.js        
npm notice 37B    dist/esm/package.json      
npm notice 90.2kB dist/umd/i18next.js        
npm notice 48.0kB dist/umd/i18next.min.js    
npm notice 90.2kB i18next.js                 
npm notice 48.0kB i18next.min.js             
npm notice 2.7kB  index.d.mts                
npm notice 16.3kB index.d.ts                 
npm notice 123B   index.js                   
**npm notice 16.3kB index.v4.d.ts**              
npm notice 5.3kB  package.json               
npm notice 358B   typescript/helpers.d.ts    
npm notice 18.0kB typescript/options.d.ts    
npm notice 8.5kB  typescript/t.d.ts          
npm notice 8.4kB  typescript/t.v4.d.ts       
npm notice === Tarball Details === 
npm notice name:          i18next                                 
npm notice version:       23.7.6                                  
npm notice filename:      i18next-23.7.6.tgz                      
npm notice package size:  131.6 kB                                
npm notice unpacked size: 614.8 kB                                
npm notice shasum:        7328e76c899052d5d33d930164612dd21e575f74
npm notice integrity:     sha512-O66BhXBw0fH4b[...]YaaXwy11kJ6YQ==
npm notice total files:   19                                      
npm notice 
i18next-23.7.6.tgz
```

I have triple checked that we have v23.7.6 installed, and do not have multiple versions or anything like that.

**Comment by adrai** [comment] 2023-11-28 13:34
@drewbrend I'm not able to reproduce the issue with TS v4 and the i18next v23.7.6 please provide a reproducible example

**Comment by drewbrend** [comment] 2023-11-28 13:39
It is not exactly easy for me to share since I'm working in a large, closed source project, I will attempt to create something.

It sounds like you were not expecting `index.v4.d.ts` to be included due to a fix for this issue.  Is is possible that the fix did not make it in as expected or is not yet released?

**Comment by adrai** [comment] 2023-11-28 14:10
I have an idea: can you try with v23.7.7 now?

**Comment by drewbrend** [comment] 2023-11-28 15:08
> I have an idea: can you try with v23.7.7 now?

From a quick build this seems to have worked!

I'll run it through our whole CI pipeline later and make sure it all works well and report back.

Thanks for the fix! 🙏

**Closed** 2023-11-28 21:39 UTC
Labels: typescript
