### ISSUE TITLE
  TypeError: i18next.createInstance is not a function from node_module

### ISSUE THREAD

**Issue by BramKaashoek** [i18next/i18next#1128] opened 2018-11-06 08:33 UTC
I am trying to test my React project using babel-jest.
One of the packages I use uses ES6 modules, so it needs to be in the transformIgnorePatterns of my jest config, so babel can transpile the files.

This node module also uses `i18next.createInstance()`, which causes problems during testing. It gives the error 'TypeError: i18next.createInstance is not a function'.

This problem does not occur when running the dev server, which uses webpack.

(partial) package.json of the consuming app is as follows:

```
  "dependencies": {
    "i18next": "^11.9.0",
}
  "devDependencies": {
    "@types/i18next": "^11.9.0",
    "babel-core": "^6.26.3",
    "babel-eslint": "7.2.3",
    "babel-jest": "^23.4.2",
    "babel-loader": "^7.1.2",
    "babel-plugin-dynamic-import-node": "^2.2.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.2",
    "babel-preset-react": "^6.24.1",
},
"jest": {
    "transform": {
      "^.+\\.jsx?$": "babel-jest",
      "^.+\\.tsx?$": "ts-jest",
      "^.+\\.js?$": "babel-jest"
    },
    "transformIgnorePatterns": [
      "/node_modules/(?!@ModuleWithI18NextAndES6Modules)"
    ],
    "testRegex": "(/__tests__/.*|(\\.|/)(test|spec))\\.(tsx?)$",
    "modulePaths": [
      "./"
    ],
  },
  "babel": {
    "presets": [
      "react",
    ],
    "plugins": [
      "transform-es2015-modules-commonjs",
      "dynamic-import-node"
    ]
  },
```

The usage of i18next within the package is as follows:

```
import * as i18next from 'i18next';
import * as LanguageDetector from 'i18next-browser-languagedetector';
import * as moment from 'moment';

const i18n = i18next
    .createInstance()
    .use(LanguageDetector)
    .init({
        resources: localeResources,
        fallbackLng: fallbackLanguages,
        react: { wait: true },
        ns: [i18nNamespace],
        defaultNS: i18nNamespace,
        debug: false,
        cache: { enabled: true },
        interpolation: {
            format(value: any, format: string | undefined) {
                if (value instanceof Date) {
                    return formatDate(value, format);
                }
                return value;
            },
        },
    });
```

In the package.json of the node module:
```
"dependencies: {
  "i18next": "^11.9.1",
}
"devDependencies":{
   "@types/i18next": "^11.9.3",
}
```

There is no problem when using the package on the dev server, there is no problem when the modules of the package are set to commonjs.

The problems only occur when using jest and the package uses es6 modules

**Comment by jamuhl** [comment] 2018-11-06 09:01
why you `import * as i18next from 'i18next';` instead of `import i18next from 'i18next';` all the i18next modules come with default export

**Comment by BramKaashoek** [comment] 2018-11-06 10:04
When I do `import i18next from 'i18next'` I get `Cannot read property createInstance of undefined`. This is using TypeScript btw.

**Comment by jamuhl** [comment] 2018-11-06 10:10
hm...console.log the `import * as i18next from 'i18next';` or `import i18next from 'i18next';` looks like that is no object at all...not importing it, unable to resolve...idk.

Best might be creating a stripped down example so we could reproduce this.

**Comment by BramKaashoek** [comment] 2018-11-06 10:32
The console.log in the package gives:
```
   I18n {
        observers: {},
        options: {},
        services: {},
        logger: 
         Logger {
           prefix: 'i18next:',
           logger: 
            { type: 'logger',
              log: [Function: log],
              warn: [Function: warn],
              error: [Function: error],
              output: [Function: output] },
           options: {},
           debug: undefined },
        modules: { external: [] } }
```

**Comment by jamuhl** [comment] 2018-11-06 10:34
makes no sense to me: should be https://github.com/i18next/i18next/blob/master/src/index.js

**Comment by BramKaashoek** [comment] 2018-11-06 12:31
Think it might be connected to the issues solved in https://github.com/i18next/react-i18next/pull/567 ?

**Comment by jamuhl** [comment] 2018-11-06 16:02
Might help to ping @schettino here...as i honestly got no idea why this happens

**Comment by schettino** [comment] 2018-11-07 16:20
no clue for now, but maybe this could be related to @types/i18next. I could work on the typings for i18next though @jamuhl

**Comment by jamuhl** [comment] 2018-11-08 08:18
@schettino would be awesome...👍

**Comment by BramKaashoek** [comment] 2018-11-08 14:52
After some reading in the source could, it would appear that the i18next object is exported before the prototype has it's extra functions (changeLanguage, createInstance, etc) added. Is this possible?

**Comment by jamuhl** [comment] 2018-11-08 14:55
the init call is what finalizes an i18n instance -> creating it based on appended (i18n.use) plugins

**Comment by jamuhl** [comment] 2018-12-03 11:33
guess you need to import like `import i18n from 'i18next'` not `import * as i18n from 'i18next'` as this is not a i18next instance -> https://github.com/i18next/i18next/blob/master/src/index.js#L5 (only the default export is a "real" instance")

**Comment by jamuhl** [comment] 2018-12-05 19:32
closing this for now...feel free to reopen if still an issue

**Closed by jamuhl** 2018-12-05 19:32 UTC
Labels: typescript
