### ISSUE TITLE
Use i18next with strict mode("use strict";) 

### ISSUE THREAD

**Issue by maulik887** [i18next/i18next#360] opened 2015-02-18 10:53 UTC
I'm having environment where I'm appending all the scripts (3rd parties[only two] + my js code) in one file, something like this-
//start of script tag

"use strict;"
//jQuery code
//i18next code
//my js code

//end of script tag

if we structure code this way, i18next library is giving error like- " Uncaught TypeError: Cannot read property 'jQuery' of undefined"

In strict mode it is not possible to reference window object so below code will fail in i18next lib. I'm wondering if is it possible to use window object instead of referencing it ? not sure about it's side effect but asking you to find out best solution here. 
![error](https://cloud.githubusercontent.com/assets/11058364/6245828/a1d9bf44-b788-11e4-8771-31ff27e38965.png)

(I know it's kind of crud way of structuring a code and I can limit 'use strict' usage in my code block instead of putting it at top but just wondering can i18next adhere to strict mode if possible?)

**Comment by jamuhl** [comment] 2015-02-18 18:49
hm..the problem is this code runs on node.js too, so using window directly will break the code...

**Comment by maulik887** [comment] 2015-02-19 10:52
oh.. yeah, To deal with similar problem what I'm doing in my other scripts is-

![code](https://cloud.githubusercontent.com/assets/11058364/6265265/35bf05ec-b852-11e4-80e8-1e7883372866.png)
I pass exports or window object as an argument of anonymous function so that within code I can do some environment specific code. I applied similar pattern in i18next library as shown above.This way it is safe to use in browser and at node side. 

I'm leaving up to you whether this fix is appropriate for i18next library or not as you have much deeper knowledge of library code. Thanks and happy coding :)

**Comment by jamuhl** [comment] 2015-02-19 13:09
will apply and test...if not causing any trouble i see no reason to not apply this

**Comment by sergioadorna** [comment] 2015-03-10 16:57
That's more or less the UMD approach, it checks for the namespace before declaring/exporting the function/class you are defining:
http://davidbcalhoun.com/2014/what-is-amd-commonjs-and-umd/#umd-universal-module-definition

it would work with requirejs/AMD, or global namespace depending on availability

**Comment by jamuhl** [comment] 2015-03-10 19:14
will be part of next version https://github.com/i18next/i18next/commit/879bcff5dd3077365f6025a43dcf59be74dbe388

hope to get that out sooner then later.

**Closed** 2015-03-10 19:15 UTC

**Comment by maulik887** [comment] 2015-03-12 11:38
Cool, thanks.
