### ISSUE TITLE
loadLanguages no-op resolved when called with the same language due to BackEndConnector bug

### ISSUE THREAD

**Issue by andrewfuchs** [i18next/i18next#1773] opened 2022-05-11 18:54 UTC
## 🐛 Bug Report

If loadLanguage is called twice with the same language, then the 2nd call will immediately resolve with no error, even though the language has yet to be loaded. This issue is due to the [code](https://github.com/i18next/i18next/blob/d4a7508e9f67aabfba81020e3f594da028cbe3dc/src/BackendConnector.js#L36) here as well as the code [here](https://github.com/i18next/i18next/blob/9c98c11e598ee2bf75ab737d9eb4c1480af706b9/src/i18next.js#L487)

## To Reproduce

loadLanguage does not need to be explicitly called twice. Calling t() or another translation function, and then using loadLanguage, will also reproduce the issue.

## Expected behavior

A loadLanguage call that intersects with a pending request should return the same promise, this way all promises resolve when the language is fully loaded.

**Comment by adrai** [comment] 2022-05-11 18:55
probably duplicate of https://github.com/i18next/i18next/issues/1772

**Comment by adrai** [comment] 2022-05-11 19:29
should be fixed with v21.8.1

**Closed by adrai** 2022-05-11 19:29 UTC
