### ISSUE TITLE
React 18  type issues -`Type 'TFunctionResult' is not assignable to type 'ReactNode'.

### ISSUE THREAD

**Issue by HT-Moh** [i18next/i18next#1750] opened 2022-04-09 20:28 UTC
`Type 'TFunctionResult' is not assignable to type 'ReactNode'.
  Type 'object' is not assignable to type 'ReactNode'.ts(2322)
[index.d.ts(1360, 9): ]()The expected type comes from property 'children' which is declared here on type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'` 

Tried  the following: 
This solution does not work. 

```
import * as i18next from 'i18next';

// Workaround for https://github.com/isaachinman/next-i18next/issues/1781
declare module 'i18next' {
  interface TFunction {
    <
      TKeys extends i18next.TFunctionKeys = string,
      TInterpolationMap extends object = i18next.StringMap
    >(
      key: TKeys,
      options?: i18next.TOptions<TInterpolationMap> | string,
    ): string;
  }
}
``` 
changing ` {t('dashboard')}``to  {t<string>('dashboard')} works, but not ideal I need to change it in almost all files. 

Related: 
https://github.com/i18next/react-i18next/issues/1477#issuecomment-1093951936 https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46691
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210

**Comment by adrai** [comment] 2022-04-10 06:56
https://github.com/i18next/react-i18next/pull/1480

**Comment by adrai** [comment] 2022-04-10 15:03
Duplicate of: https://github.com/i18next/react-i18next/issues/1476

**Closed** 2022-04-10 15:04 UTC
Labels: typescript

**Comment by adrai** [comment] 2022-04-10 16:09
v11.16.4 fixes this

**Comment by ferdicus** [comment] 2022-05-11 15:24
> v11.16.4 fixes this

hi there, this assumes one uses `react-i18next`? (there version of this repo as of writing this comment is 21.8.0)
what if one uses "just" `i18next`?

**Comment by adrai** [comment] 2022-05-11 15:27
> > v11.16.4 fixes this
> 
> 
> 
> hi there, this assumes one uses `react-i18next`? (there version of this repo as of writing this comment is 21.8.0)
> 
> what if one uses "just" `i18next`?

You are using i18next in React without react-i18next?
Maybe @pedrodurek can advice?

**Comment by ferdicus** [comment] 2022-05-11 15:35
> You are using i18next in React without react-i18next?

Correct, maybe I'm doing it wrong 🤔, however I like to keep my dependencies low and `i18next` already does what I need: use the value of a key based on a lang json

**Comment by ferdicus** [comment] 2022-07-01 07:38
hi there, any news on this?

**Comment by Livijn** [comment] 2022-07-24 08:11
I also use `i18next` without `react-i18next`. I am experiencing the same issue.

**Comment by Livijn** [comment] 2022-12-07 09:09
Fixed it by re-defining the function:

```ts
const t = (text: string, object: AnyObject | undefined = undefined): string =>
  i18n.t(text, object);
```
