### ISSUE TITLE
TypeScript 5 introduced new const generic

### ISSUE THREAD

**Issue by dilame** [i18next/i18next#1950] opened 2023-04-29 19:38 UTC
In the [typescript section of your documentation](https://www.i18next.com/overview/typescript#type-error-template-literal) you rely on user to provide `value as const`. 

> TypeScript will lose the literal value, and it will infer the key as string, which will cause to throw the error above. In this case, you will need to assert the template string as const, like this:

In the latest TypeScript release they introduced new [const type parameters](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#const-type-parameters), i think you could be interested in it.

**Comment by adrai** [comment] 2023-04-29 19:39
https://github.com/i18next/i18next/pull/1911

**Comment by Darhagonable** [comment] 2023-05-04 15:47
duplicate of #1929

**Comment by adrai** [comment] 2023-06-15 09:46
Please try with i18next v23.0.1 and react-i18next v13.0.0

**Closed** 2023-08-12 17:14 UTC
Labels: typescript
