### ISSUE TITLE
Deault values in t function do not work

### ISSUE THREAD

**Issue by Toto5931** [i18next/i18next#2124] opened 2024-01-24 22:05 UTC
## 🐛 Bug Report

Default values in t function do not work

## To Reproduce

```js
              t("key1", {count: 0,
			defaultValue_zero: "no item",
			defaultValue_one: "one item",
			defaultValue_other: "{{count}} items",
		})
renders: one item
```

## Expected behavior
It renders "one item" whereas I would have expected zero.
If I put this in a traduction file it works but I want my code to be the source of thruth.

## Your Environment

- *runtime version*:  browser 
- *i18next version*: 23.7.18
- *os*:  Windows
- *any other relevant information*

**Comment by adrai** [comment] 2024-01-24 22:42
should be fixed with i18next v23.7.19

**Comment by Toto5931** [comment] 2024-01-26 11:19
Thanks. It works if saveMissing: false

But in [this sandbox example](https://codesandbox.io/p/sandbox/i18n-bug-fcr6pm?file=%2Fsrc%2Findex.js%3A5%2C17&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clruhryyf0006356f66ymkwb4%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clruhryye0002356fph4j4alu%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clruhryye0003356f3t05p4rl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clruhryye0005356fp620u80r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clruhryye0002356fph4j4alu%2522%253A%257B%2522id%2522%253A%2522clruhryye0002356fph4j4alu%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clruipngx0002356fh7v452t9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A10%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A12%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clruj31tt0002356fsxz4muey%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A22%252C%2522startColumn%2522%253A4%252C%2522endLineNumber%2522%253A22%252C%2522endColumn%2522%253A15%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fi18n.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clruj4zyq0002356fatgkebop%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A17%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A17%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clruj4zyq0002356fatgkebop%2522%257D%252C%2522clruhryye0005356fp620u80r%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clruhryye0004356fi9nt9oww%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clruhryye0005356fp620u80r%2522%252C%2522activeTabId%2522%253A%2522clruhryye0004356fi9nt9oww%2522%257D%252C%2522clruhryye0003356f3t05p4rl%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clruhryye0003356f3t05p4rl%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A20.25%257D) as soon as I activate saveMissing:true, the displays goes to "one item def" instead of "no item def". 

And the POST requests are {key12_one: "one item def"}, {key12_other: "{{count}} items def"} and {key12_many: "no item def"} whereas I would have expected key12_zero instead of key12_many

**Comment by adrai** [comment] 2024-01-26 12:02
That's because of the fallbackLng it defaults to dev....
We've just released v23.7.20 that should address this.

**Comment by Toto5931** [comment] 2024-01-26 15:57
Thank you for your quick response

There is still one problem, [in this sandox example](https://codesandbox.io/p/devbox/i18n-bug-fcr6pm?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clruhryyf0006356f66ymkwb4%2522%252C%2522sizes%2522%253A%255B76.7019667170953%252C23.298033282904697%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clruhryye0002356fph4j4alu%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clruhryye0003356f3t05p4rl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clruhryye0005356fp620u80r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clruhryye0002356fph4j4alu%2522%253A%257B%2522id%2522%253A%2522clruhryye0002356fph4j4alu%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clruipngx0002356fh7v452t9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A34%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A34%257D%255D%257D%252C%257B%2522id%2522%253A%2522clruj31tt0002356fsxz4muey%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A21%252C%2522startColumn%2522%253A23%252C%2522endLineNumber%2522%253A21%252C%2522endColumn%2522%253A23%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fi18n.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clruj4zyq0002356fatgkebop%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A17%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A17%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clruj31tt0002356fsxz4muey%2522%257D%252C%2522clruhryye0005356fp620u80r%2522%253A%257B%2522id%2522%253A%2522clruhryye0005356fp620u80r%2522%252C%2522activeTabId%2522%253A%2522clrupvhfb006d356fuubv4flg%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clrupvhfb006d356fuubv4flg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clruhryye0003356f3t05p4rl%2522%253A%257B%2522id%2522%253A%2522clruhryye0003356f3t05p4rl%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clrupvfau004r356f2bwod614%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrupvfau004r356f2bwod614%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A20.25%257D)  {key_many: "no item def"} is sent in POST whereas it is not defined in the default value. Moreover it takes the value of key_zero, which makes no sense. 

For your information, if we change the order of the ressource from 
```
    translation: {
      key_one: "{{count}} item",
      key_other: "{{count}} items",
      key_zero: "no item",
    },
```
to 
```
    translation: {
      key_zero: "no item",
      key_one: "{{count}} item",
      key_other: "{{count}} items",
    },
```
the problem does not happen.

Thanks !

**Comment by adrai** [comment] 2024-01-26 17:19
currently afk... but I guess that's because of the used language...
_zero is sent if there is also a defaultValue_zero provided

**Comment by adrai** [comment] 2024-01-26 21:39
i'm not able to reproduce your issue...

**Comment by Toto5931** [comment] 2024-01-27 14:46
The issue is reproduced in the sandbox link I gave. Try refreshing several times since the network exchanges are not always displayed (I don't know why)
See the capture below. "_many" is sent in POST whereas it is not defined as default. And its value is the one of "_zero" so it is dangerous.
![Capture](https://github.com/i18next/i18next/assets/36714085/07d5a1e7-0d9b-4a95-8df8-5d272f995180)
Thanks !

**Comment by adrai** [comment] 2024-01-27 15:49
It's not because of the refresh... it's because of the detected language... that's why I'm not able to reproduce it... for me it detects english... for you probably french...
if I add ?lng=fr in the url, I can also see the key_many... but this is correct for french... this occurs, because you set the fallbackLng to false...
try to set it to en => fallbackLng: 'en',

**Comment by Toto5931** [comment] 2024-01-27 18:33
What is the link between the fallbackLng and the fact that it sends _many whereas it does not exist?
I need to keep fallbackLng to false since I do not want that he loads 2 language files when 1 language is enough

**Comment by adrai** [comment] 2024-01-27 19:09
The reason is the saveMissingTo option: https://www.i18next.com/overview/configuration-options

**Closed** 2024-02-17 12:45 UTC
