### ISSUE TITLE
sprintf does not work with shortcutFunction and falsey first argument

### ISSUE THREAD

**Issue by benjyblack** [i18next/i18next#451] opened 2015-11-10 16:31 UTC
As shown in [this jsfiddle](http://jsfiddle.net/dLc7x/56/).

To reproduce:

1. Set shortcut function to `sprintf`
2. Attempt to do a translation with a falsey first sprintf argument (ex. `$.t('There are %d items', 0)`)
3. Notice the output does not  replace the token.

It's due to [this line](https://github.com/i18next/i18next/blob/master/i18next.js#L1507). You should probably check to see if the shortcutFunction is set here before assuming the second argument is supposed to be the options object.

**Comment by jamuhl** [comment] 2015-11-11 06:43
will be fixed in next version - PR would be welcome - as currently i'm more focused on getting i18next v2 out

**Closed** 2015-11-12 13:13 UTC
Labels: issue

**Comment by iandarlingmnetics** [comment] 2016-04-15 14:50
I believe this PR has broken defaultValue support in 1.11.1 and 1.11.2

[This code change](https://github.com/i18next/i18next/compare/1.11.0...1.11.1#diff-e171f9b8b4e0f5df027bd8bd7b962f1bR1512) appears to be the culprit - it's a typo "options.detaultValue"

**Comment by jamuhl** [comment] 2016-04-15 15:15
@iandarlingmnetics this is an issue in v1.11.x. that code did not made it into v2.x.x. The issue is only visible in edge cases where t function is accessed before initialization. Won't publish a v1.11.3 for that...as it is a non breaking issue.
