### ISSUE TITLE
Testing with i18next and mocha

### ISSUE THREAD

**Issue by hovancik** [i18next/i18next#1003] opened 2017-12-06 10:45 UTC
Hi, I've added i18next to my project and I'm having troubles with testing. 
I run my test with `mocha test`
Here's example of what I did before: 

file I wanna test 
```
let formatRemaining = function (seconds) {
  if (seconds < 60) {
    return `${seconds} seconds left`
  } else {
    return`${Math.trunc((seconds / 60) + 1)} seconds left`
  }
}
module.exports.formatRemaining = formatRemaining

```
test file
```
const chai = require('chai')
const Utils = require('../app/utils/utils')
chai.should()

describe('Utils', function () {
  it('formats remaining seconds into correct format', function () {
    Utils.formatRemaining(10).should.equal('11 seconds left')
    Utils.formatRemaining(60).should.equal('2 minutes left')
    Utils.formatRemaining(61).should.equal('2 minutes left')
    Utils.formatRemaining(150).should.equal('3 minutes left')
  })
})

```

What I'm trying with i18next: 

file I wanna test 
```
const i18next = require('i18next')

let formatRemaining = function (seconds) {
  if (seconds < 60) {
    return i18next.t('utils.secondsLeft', {count: seconds + 1})
  } else {
    return i18next.t('utils.minutesLeft', {count: Math.trunc((seconds / 60) + 1)})
  }
}

module.exports.formatRemaining = formatRemaining
```

test file:
```
const chai = require('chai')
const Utils = require('../app/utils/utils')
const i18next = require('i18next')
const Backend = require('i18next-node-fs-backend')
i18next
  .use(Backend)
  .init({
    lng: 'en',
    fallbackLng: 'en',
    debug: false,
    backend: {
      loadPath: `${__dirname}/../app/locales/{{lng}}.json`,
      jsonIndent: 2
    }
  }, function (err, t) {
    i18next.changeLanguage('en')
    if (err) {
      console.log(err.stack)
    }
  })

chai.should()

describe('Utils', function () {
  it('formats remaining seconds into correct format', function () {
    Utils.formatRemaining(10).should.equal('11 seconds left')
    Utils.formatRemaining(60).should.equal('2 minutes left')
    Utils.formatRemaining(61).should.equal('2 minutes left')
    Utils.formatRemaining(150).should.equal('3 minutes left')
  })
})
```

and I'm getting: 

```
  Utils
       formats remaining seconds into correct format:
     TypeError: Cannot read property 'should' of undefined
      at Context.<anonymous> (test/utils.js:26:30)
```

When I put debug to true, I see that i18next starts fine. 

Any ideas what am I doing wrong?

**Comment by jamuhl** [comment] 2017-12-06 10:51
the problem i see is i18next does init async - so loading of translations is done sometime in the flow...might be after calling the it blocks.

you might add the i18next init block to some `before` block calling done in init callback

**Comment by hovancik** [comment] 2017-12-06 11:09
So I've tried the following: 

```
describe('Utils', function () {
  beforeEach(function (done) {
    i18next
      .use(Backend)
      .init({
        lng: 'en',
        fallbackLng: 'en',
        debug: false,
        backend: {
          loadPath: `${__dirname}/../app/locales/{{lng}}.json`,
          jsonIndent: 2
        }
      }, function (err, t) {
        i18next.changeLanguage('en')
        if (err) {
          console.log(err.stack)
        }
        done()
      })
  })

  it('formats remaining seconds into correct format', function () {
    console.log('Utils', Utils.formatRemaining(10))
    Utils.formatRemaining(10).should.equal('11 seconds left')
    Utils.formatRemaining(60).should.equal('2 minutes left')
    Utils.formatRemaining(61).should.equal('2 minutes left')
    Utils.formatRemaining(150).should.equal('3 minutes left')
  })
```

The error changes a bit: 

```
      formats remaining seconds into correct format:
     TypeError: Cannot read property 'should' of undefined
      at Context.<anonymous> (test/utils.js:31:30)
      at test/utils.js:25:9
      at node_modules/i18next/dist/commonjs/i18next.js:195:9
      at done (node_modules/i18next/dist/commonjs/i18next.js:298:21)
      at Object.callback (node_modules/i18next/dist/commonjs/i18next.js:312:9)
      at node_modules/i18next/dist/commonjs/BackendConnector.js:152:13
      at Array.forEach (native)
      at Connector.loaded (node_modules/i18next/dist/commonjs/BackendConnector.js:139:16)
      at node_modules/i18next/dist/commonjs/BackendConnector.js:287:14
      at node_modules/i18next/dist/commonjs/BackendConnector.js:180:7
      at node_modules/i18next-node-fs-backend/lib/index.js:124:9
      at node_modules/i18next-node-fs-backend/lib/index.js:86:9
      at tryToString (fs.js:449:3)
      at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```

**Comment by jamuhl** [comment] 2017-12-06 11:18
looks related to chai.should -> could you try the expect API of chai?

`expect(Utils.formatRemaining(10)).to.equal('11 seconds left')` if i remember right

**Comment by hovancik** [comment] 2017-12-06 11:58
So I added `let expect = chai.expect` and changed to `    expect(Utils.formatRemaining(10)).to.equal('11 seconds left')
`
error is: 

```
       formats remaining seconds into correct format:
     AssertionError: expected undefined to equal '11 seconds left'
      at Context.<anonymous> (test/utils.js:29:42)
      at test/utils.js:24:9
      at node_modules/i18next/dist/commonjs/i18next.js:195:9
      at done (node_modules/i18next/dist/commonjs/i18next.js:298:21)
      at Object.callback (node_modules/i18next/dist/commonjs/i18next.js:312:9)
      at node_modules/i18next/dist/commonjs/BackendConnector.js:152:13
      at Array.forEach (native)
      at Connector.loaded (node_modules/i18next/dist/commonjs/BackendConnector.js:139:16)
      at node_modules/i18next/dist/commonjs/BackendConnector.js:287:14
      at node_modules/i18next/dist/commonjs/BackendConnector.js:180:7
      at node_modules/i18next-node-fs-backend/lib/index.js:124:9
      at node_modules/i18next-node-fs-backend/lib/index.js:86:9
      at tryToString (fs.js:449:3)
      at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```

**Comment by jamuhl** [comment] 2017-12-06 12:03
strange ... seems Utils.formatRemaining(10) returns undefined...which can't be caused by i18next cause t will return the key if not having data loaded...but there must be something with that function wrong

could you `console.log(Utils.formatRemaining, Utils.formatRemaining(10))` ?!?

**Comment by hovancik** [comment] 2017-12-06 12:10
I gives: 

```
[Function: formatRemaining] undefined
10
I18n {
  observers: {},
  options: {},
  services: {},
  logger:
   Logger {
     prefix: 'i18next:',
     logger:
      { type: 'logger',
        log: [Function: log],
        warn: [Function: warn],
        error: [Function: error],
        output: [Function: output] },
     options: {},
     debug: undefined },
  modules: { external: [] } }
[Function: t]
undefined
```

I've addes some log inside the `formatRemaining`: 

```
  console.log(i18next)
  console.log(i18next.t)
  console.log(i18next.t('utils.secondsLeft', {count: seconds + 1}))
```

**Comment by jamuhl** [comment] 2017-12-06 12:20
hm...ok that t call returns undefined...that's strange...evtl. not initialized at all or some errors loading the translations?!? could you set debug = true and see if backend loads the actual translations

or if there is an error in init callback?!? `i18next.init(options, (err, t) => {})`

or `console.log(i18next.services.resourceStore.data)`

**Comment by hovancik** [comment] 2017-12-06 13:16
```
i18next::backendConnector: loaded namespace translation for language en { // my translations
}
i18next: languageChanged en
i18next: initialized { debug: true,
  initImmediate: true,
  ns: [ 'translation' ],
  defaultNS: [ 'translation' ],
  fallbackLng: [ 'en' ],
  fallbackNS: false,
  whitelist: false,
  nonExplicitWhitelist: false,
  load: 'all',
  preload: false,
  simplifyPluralSuffix: true,
  keySeparator: '.',
  nsSeparator: ':',
  pluralSeparator: '_',
  contextSeparator: '_',
  saveMissing: false,
  saveMissingTo: 'fallback',
  missingKeyHandler: false,
  postProcess: false,
  returnNull: true,
  returnEmptyString: true,
  returnObjects: false,
  joinArrays: false,
  returnedObjectHandler: [Function: returnedObjectHandler],
  parseMissingKeyHandler: false,
  appendNamespaceToMissingKey: false,
  appendNamespaceToCIMode: false,
  overloadTranslationOptionHandler: [Function: handle],
  interpolation:
   { escapeValue: true,
     format: [Function: format],
     prefix: '{{',
     suffix: '}}',
     formatSeparator: ',',
     unescapePrefix: '-',
     nestingPrefix: '$t(',
     nestingSuffix: ')',
     maxReplaces: 1000 },
  lng: 'en',
  backend:
   { loadPath: '/Users/janhovancik/workspace/hovancik/stretchly/test/../app/locales/{{lng}}.json',
     jsonIndent: 2 } }
```

I've printed `i18next.services.resourceStore.data` inside my test and I see my translations. Inside Utils, it gives `TypeError: Cannot read property 'data' of undefined`

**Comment by jamuhl** [comment] 2017-12-06 13:44
weird...something is wrong but honestly i can't tell you what without debugging through your code...

**Comment by hovancik** [comment] 2017-12-06 15:42
It's really weird. I've tried with new project just with this one test and it works fine. So I figured out `"electron-builder": "^19.43.4",` is causing it.

**Comment by jamuhl** [comment] 2017-12-06 15:43
wow...really strange...

**Comment by hovancik** [comment] 2017-12-07 08:03
I have example repo here: https://github.com/hovancik/i18next-test
Will also open issue with electron-builder

**Comment by jamuhl** [comment] 2018-01-11 13:25
any update on this?

**Comment by hovancik** [comment] 2018-01-11 13:28
Hi, no answer from electon-builder team. I've commented out my tests...
I guess we can close this issue.

**Comment by jamuhl** [comment] 2018-01-11 13:29
sad to hear that...closing for now...thanks for reporting back

**Closed by jamuhl** 2018-01-11 13:29 UTC
Labels: question / configuration

**Comment by hovancik** [comment] 2020-04-25 08:41
Hey @jamuhl , I am coming back to this and I am trying something different.

Before my function was sth like: `const formatTimeRemaining = function (milliseconds)`. It came to me that I could try `const formatTimeRemaining = function (milliseconds, i18next = require('i18next'))`.

In App, it would take `require` and it test I would do: `formatTimeRemaining(100, i18next).should.equal('1 second remaining')`

First, I was excited because it worked (somehow) but now I am mostly getting: 

```
      AssertionError: expected 'utils.secondsRemaining' to equal '1 second remaining'
      + expected - actual

      -utils.secondsRemaining
      +1 second remaining
```

This is my test: 

```
const chai = require('chai')
const { formatTimeRemaining } = require('../app/utils/utils')
const i18next = require('i18next')
const Backend = require('i18next-node-fs-backend')
// const sinon = require('sinon')

chai.should()

describe('Utils', function () {
  beforeEach(() => {
    i18next
      .use(Backend)
      .init({
        lng: 'en',
        fallbackLng: 'en',
        debug: false,
        backend: {
          loadPath: `${__dirname}/../app/locales/{{lng}}.json`,
          jsonIndent: 2
        }
      }, function (err, t) {
        if (err) {
          console.log(err)
          console.error(err.stack)
        }
      })
  })
  it('formats remaining seconds into correct format', function () {
    formatTimeRemaining(100, i18next).should.equal('1 second remaining')
  })
})
```
This is my function: 
```
const formatTimeRemaining = function (milliseconds, i18next = require('i18next')) {
  const seconds = Math.ceil(milliseconds / 1000.0)
  const minutes = Math.ceil(seconds / 60.0)
  const hours = Math.ceil(minutes / 60.0)
  if (seconds < 60) {
    return i18next.t('utils.secondsRemaining', { seconds: seconds })
  }
  if (seconds >= 60 && minutes < 60) {
    return i18next.t('utils.aboutMinutesRemaining', { minutes: minutes })
  }
  if (minutes >= 60) {
    if (minutes % 60 === 0) {
      return i18next.t('utils.aboutHoursRemaining', { hours: hours })
    } else if (minutes === 60) {
      return i18next.t('utils.aboutHoursRemaining', { hours: hours + 1 })
    } else {
      return i18next.t('utils.aboutHoursMinutesRemaining', { minutes: minutes, hours: hours })
    }
  }
  return 'Uknown'
}
```

And those are translations: 

```
  "utils": {
    "seconds": "{{count}} second",
    "seconds_plural": "{{count}} seconds",
    "minutes": "{{count}} minute",
    "minutes_plural": "{{count}} minutes",
    "hours": "{{count}} hour",
    "hours_plural": "{{count}} hours",
    "secondsRemaining": "$t(utils.seconds, {'count': {{seconds}} }) remaining",
    "aboutMinutesRemaining": "About $t(utils.minutes, {'count': {{minutes}} }) remaining",
    "aboutHoursRemaining": "About $t(utils.hours, {'count': {{hours}} }) remaining",
    "aboutHoursMinutesRemaining": "About $t(utils.hours, {'count': {{hours}} }) $t(utils.minutes, {'count': {{minutes}} }) remaining",
    "inSeconds": "in $t(utils.seconds, {'count': {{seconds}} })",
    "inAboutMinutes": "in about $t(utils.minutes, {'count': {{minutes}} })",
    "inAboutHours": "in about $t(utils.hours, {'count': {{hours}} })",
    "inAboutHoursMinutes": "in about $t(utils.hours, {'count': {{hours}} }) $t(utils.minutes, {'count': {{minutes}} })"
  },
```

As app works, I feel like I am missing some small thing here, maybe you can see what?

**Comment by hovancik** [comment] 2020-04-25 08:46
@jamuhl , hey sorry I figured it out ;] 
I turned on debug and 
```
i18next: hasLoadedNamespace: i18next was not initialized undefined
i18next::translator: key "utils.secondsRemaining" for namespace "translation" for languages "en" won't get resolved as namespace was not yet loaded This means something IS WRONG in your application setup. You access the t function before i18next.init / i18next.loadNamespace / i18next.changeLanguage was done. Wait for the callback or Promise to resolve before accessing it!!!
```
I moved it out of `beforeEach` and it works! Yay, feels like hack to me but it works :)
```

**Comment by hovancik** [comment] 2020-04-25 08:51
Okay, so I was too fast. Sometimes it works, sometimes it fails with that message from debug.

**Comment by jamuhl** [comment] 2020-04-25 09:11
Are you async loading the translations using a backend?

**Comment by hovancik** [comment] 2020-04-25 09:43
Yeah, I did :) Thanks for pointing me into right direction. 

If anyone comes to the same problem, here is how I fixed it: 

```
  beforeEach(function (done) {
    i18next
      .use(Backend)
      .init({
        lng: 'en',
        fallbackLng: 'en',
        debug: true,
        backend: {
          loadPath: `${__dirname}/../app/locales/{{lng}}.json`,
          jsonIndent: 2
        }
      }, function (err, t) {
        if (err) {
          console.log(err)
          return done(err)
        }
        done()
      })
  })
```

Seems to pass every time :) 

Thanks for help!

**Comment by hovancik** [comment] 2021-02-23 10:13
Hi @jamuhl , has something important changed between `19.8.7` and `19.8.8/9`? 

I am getting the same issue as I had before my fix, I guess: 

```
i18next::translator: key "utils.inSeconds" for languages "en" won't get resolved as namespace "translation" was not yet loaded This means something IS WRONG in your setup. You access the t function before i18next.init / i18next.loadNamespace / i18next.changeLanguage was done. Wait for the callback or Promise to resolve before accessing it!!!
i18next::translator: missingKey undefined translation utils.inSeconds utils.inSeconds
```

**Comment by adrai** [comment] 2021-02-23 11:23
@hovancik can you verify you call init function only once?
If not, you may use createInstance

**Comment by hovancik** [comment] 2021-02-23 11:52
Thanks! It was that, so I changed the `beforeEach` to `before` as it was not needed to init every test.
