### ISSUE TITLE
Get and change the server url that i18next try to get translation resources from it

### ISSUE THREAD

**Issue by Shereind** [i18next/i18next#1107] opened 2018-09-30 09:50 UTC
I'm developing chrome plugin where I add <div> tags to different internet pages (different url's)
so when I try to translate the <div> I added to the page. I got an exception for file not found because i18next try to get translation file from this page server URL :
"http://sass-lang.com/locales/en/translation.json"
** http://sass-lang.com is the URL I'm running my plugin on it.
![image](https://user-images.githubusercontent.com/42438027/46256130-44f49280-c4af-11e8-977e-a71f560bc733.png)

How to set or change server URL that i18next use to my constant local files in my code?

**Comment by jamuhl** [comment] 2018-09-30 14:04
if you add translations on init -> remove the backend and add resources like -> https://www.i18next.com/how-to/add-or-load-translations#add-on-init

like said in your other issue...how you add / bundle local files depend on your bundler -> i linked you already a sample for using imports when using webpack

**Comment by jamuhl** [comment] 2018-09-30 14:05
duplicate of: https://github.com/i18next/i18next/issues/1106

**Closed by jamuhl** 2018-09-30 14:05 UTC
