### ISSUE TITLE
Regional variations fall back to regionless before specified fallbackLng rules

### ISSUE THREAD

**Issue by markdon** [i18next/i18next#1506] opened 2020-09-18 00:11 UTC
## To Reproduce
[Try out this codesanbox](https://codesandbox.io/s/react-i18next-example-forked-93st2?file=/src/i18n.js)
Review fallbackLangs in i18n.js. The configuration is intended to make 'en-GB' fall back to 'en-AU'.
Click the 'en-GB' button.
The 'Welcome to React' header shows the 'en' translation instead of 'en-AU' translation.

## Expected behavior

When a language is specified in fallbackLngs with a set of languages to fall back to and i18next changes to that language, i18next should try to use the fallback languages in the order they were specified.

## Your Environment
Codesandbox 🤷‍♂️
![image](https://user-images.githubusercontent.com/9063681/93540420-f475e880-f996-11ea-83db-e199a9e3f66a.png)
My actual project is a bit different, with http-backend, but this simple codesanbox also reproduces.

**Comment by jamuhl** [comment] 2020-09-18 06:32
The cause is i18next per default uses the language based on the locale as a first fallback. So given `en-GB` i18next will try with the neutral `en` before going to any fallback. https://www.i18next.com/principles/fallback#language-fallback

You can turn that of by setting option: `load: "currentOnly"` which will stop doing that en-GB -> en fallback.

just a reminder -> there is no option `wait` for react-i18next (that was removed long ago and replaced with Suspense usage)

**Comment by markdon** [comment] 2020-09-22 07:17
Thanks for looking at this for me @jamuhl! 

I had experimented with the `load: "currentOnly"` setting, but in general I do want to take advantage of the standard non-region fallback. I have around 30 supported languages which have a huge amount of regional variations that don't have translations. Managing the list of fallbacks without `load: "all"` and the non-region fallback would be very impractical.

It seems sensible to me that if a fallback rule was specified for a language that the default non-region fallback would be ignored since the rule can include falling back to the non-regional language.

There might be other weird things in the codesandbox! I forked someone else's and updated it to latest.

**Comment by jamuhl** [comment] 2020-09-22 07:30
the point is: i18next builds an order on how it lookup keys: 

so having `load: all` it will be for eg. 

en-US -> en -> fallback =====> en

what you want is:

en-US -> fallback -> en =====> en-AU as defined in your fallback

So like you say: 

> It seems sensible to me that if a fallback rule was specified for a language that the default non-region fallback would be ignored since the rule can include falling back to the non-regional language.

So why would one prefer one setting the locale to `en-US` getting `en-AU` translations over `en` (what is even the difference between en-AU and en? en is whatever slang you take as there is no real en -> most cases that is either some variation of britisch english (oxford, Cambridge) or US amerikan or Austalian english...or developer english)

**Comment by markdon** [comment] 2020-09-29 01:07
> en is whatever slang you take as there is no real en

That's exactly the reason why I don't want `en-GB` to fall back to `en`. `en` will always be a specific regional variation. In our case it's `en-US` since we're working for an American company and even though the English might be considered the ones who use proper English, there are more Americans and people in other countries that learn American English.

We are maintaining `en-AU` languages since we can do it ourselves. We can't easily maintain other regional variations of English. We do know that `en-GB` is much closer to `en-AU` than it is `en-US`. So having `en-GB` fall back to `en-AU` is preferable instead of `en` (which is `en-US`). Now that I think of it... There are other regions that this can apply to e.g. `en-NZ`, `en-IE`.

This situation might also apply to different languages like Spanish, which is spoken across a broad area. We might want _unknown_ regional variations to default to a North American variation of Spanish (using the `load: "all"` `es` fallback) and specify some known South American regions to fall back to a single South American variation (using a defined rule in `fallbackLng`).

It is not currently possible to use the automatic `load: "all"` fallback for unknown regions while also specifying rules for known regions.

**Comment by jamuhl** [comment] 2020-09-29 03:00
If you like provide a PR (including needed tests) adding a feature to give fallbacks from a function here:

https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L122

`if (typeof fallbacks === 'function') fallbacks = fallbacks(code)``

Your fallback function can then return whatever you like including the "languageOnly" part (eg. en) at the end. So combining this with `load: 'currentOnly'` you get your needed functionality.

**Comment by alexmarles** [comment] 2020-09-29 15:48
> This situation might also apply to different languages like Spanish, which is spoken across a broad area. We might want _unknown_ regional variations to default to a North American variation of Spanish (using the `load: "all"` `es` fallback) and specify some known South American regions to fall back to a single South American variation (using a defined rule in `fallbackLng`).

This is exactly what is happening to us. We support Mexican Spanish but we want all other Spanish variations to fallback to "regular" Spanish. If we use `load: "all"` there is a problem with different platforms using different ISO codes.

For example, on iOS12 Mexican is shown as `es-LX`, but in iOS13 shows as `es-419`, and in Android is `es-MX`, so we need to specify the fallback options for the different codes used.

This can only be achieved if we set `load: "currentOnly"`, but then we are forced to specify all the variations for all possible languages, including different regions of Chinese (simplified and traditional) which can be problematic.

The best option would be to be able to use the automatic fallback to language only but being able to specify fallback rules for specific regional variations.

**Comment by jamuhl** [comment] 2020-09-29 16:03
@alexmarles https://github.com/i18next/i18next/issues/1506#issuecomment-700396665 enables that...just combine your fallback logic with adding https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L29 as last option

**Comment by alexmarles** [comment] 2020-09-29 18:33
I see. This will allow us to have our own hierarchy of language variations, although I think this should be addressed at a deeper level.

Right now, when resolving hierarchy [it places the fallback codes as last option](https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L162) in the final `codes` array, and the base variation fallback code is placed before those, thus ignoring the whole fallback logic if the main language translations exist (ie: `es` will always be first if we have `es-MX` as fallback for some cases).

In my opinion, this way of handling the fallback options is misleading because it ignores any resolution to regional variations in favor to base languages variations.

**Comment by jamuhl** [comment] 2020-09-29 18:59
Look fallback always was:

1) what was given by detector: eg. `en-US`
2) at least lookup in the language part of the locale: `en`
3) not found -> fallback to the fallback language: `de` (mostly source language of the project)

So basically...my locale is `de-CH` (swiss german) -> I prefer any `de` variation before you give me any `es` fallback.

Fallbacks like en-GB to en-AU keeping en as en-US...or we like es-MX to fallback to en-419 was never in scope. 

Your goal should be to make sure en-GB or es-MX is completely translated - fallback are a bad thing and only there as a safety net.

Anyway...if you got a better suggestion changing the code than my above suggestion - go for it...but I won't accept breaking existing behavior.

**Comment by alexmarles** [comment] 2020-09-29 19:48
You are right that the intended purpose of fallbacks was not to cover this specific regional cases in the first place, and I understand.

In my case the issue is not that `es-MX` is not fully translated (because it is), but to be able to fallback to `es-MX` from other specific codes **before** relying on the general `es` translation (in my case, because some platforms don't use the same codes for this variation).

Anyways, I worked on a solution following what you said, I will send a PR shortly.

**Comment by markdon** [comment] 2020-09-29 23:52
> @alexmarles [#1506 (comment)](https://github.com/i18next/i18next/issues/1506#issuecomment-700396665) enables that...just combine your fallback logic with adding https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L29 as last option

Thanks for showing us where this would go @jamuhl. A function to resolve fallback languages will add a lot of flexibility.

@alexmarles If you're interested in a free tshirt for your PRs, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/)!

**Comment by markdon** [comment] 2020-10-01 23:51
This didn't look like it would take long, so I gave it a shot.

**Comment by jamuhl** [comment] 2020-10-02 11:18
published in i18next@19.8.0

**Closed by jamuhl** 2020-10-02 11:18 UTC

**Comment by alexmarles** [comment] 2020-10-02 12:40
That's great @markdon! I didn't had the time to send the PR because I wanted to give some more thoughts. Your solution looks even cleaner 😅 

Just to be clear, with this solution if I want `es-419` to fallback to `es-MX` before than `es` I should write a fallback function similar to this:
```js
fallbackLng: (locale) => ({
    'es-419': ['es-MX', 'es']
    default: ['en'],
})
```

And use it in conjunction with `load: currentOnly`. Is that right?

I also could add something like `locale.split('-')[0]` to the first position of the default array so I can capture things like `fr-FR` and send it to `fr`.

**Comment by markdon** [comment] 2020-10-03 00:07
You need to programmatically include the regionless fallback for your other language codes so that you get that functionality at the same time as using 'load : "currentOnly"'.

No matter the return type from your function, the rest of the fallback code will behave as if you had set fallbackLngs to that value.

I wrote an example which is a full implementation similar to what you're looking for: https://github.com/i18next/i18next-gitbook/pull/140/commits/94d3b18e78b802a599c9f0cf9fc45e56bd63b850

**Comment by Jacob-Roberts** [comment] 2024-02-05 11:22
A proper solution to this would be to use the CLDR Enhanced matching algorithm.

For this, we use `@phensley/cldr`.

And for us the proper fix was to actually change the detector logic. Our i18next detection options look like this

```ts
detection: {
      order: process.env.NODE_ENV === "development" ? ["navigator"] : undefined, // In dev, when working on detecting language, the local storage cache gets in the way.
      convertDetectedLanguage: (lng) => {
        if (lng === "pseudo") return lng
        const closestLang = closestSupportedMatch(lng)
        console.debug("Detected language: ", lng, "closest: ", closestLang)
        return closestLang
      },
    },
```

And then our `closestSupportedMatch` function is defined as such

```ts
import { LocaleMatcher } from "@phensley/cldr"
import type { SupportedLanguage } from "./settings"
import { fallbackLng, supportedLanguages } from "./settings"

const localeMatcher = new LocaleMatcher(supportedLanguages)

/** Get the closest matched language that we support. If no match, the default language will be returned.
 * This uses the CLDR Enhanced Language Matching algorithm. https://www.unicode.org/reports/tr35/tr35.html#EnhancedLanguageMatching
 */
export function closestSupportedMatch(desiredLanguage: string | string[]): SupportedLanguage {
  const { locale, distance } = localeMatcher.match(desiredLanguage)
  console.table({
    desired_language: desiredLanguage,
    closest: locale.id,
    full_tag: locale.tag.expanded(),
    distance,
  })
  if (supportedLanguages.includes(locale.id as SupportedLanguage)) {
    return locale.id as SupportedLanguage
  }
  return fallbackLng
}

```

And our server side works the same way. We take the `Accept-Language` header, and call these functions on it

```ts
/**
 * Get matched language. If no match, the default language will be returned.
 * @param priorityList A comma-separated list of language tags, with optional quality values. Can be taken directly from the `Accept-Language` header.
 */
export function acceptedLanguagesHelper(priorityList: string): SupportedLanguage {
  const priorityListArray = parseAndSortLanguageTags(priorityList)
  return closestSupportedMatch(priorityListArray.map((i) => i.tag))
}

function parseAndSortLanguageTags(languagePriorityList: string) {
  return languagePriorityList
    .split(",")
    .map(function (weightedLanguageRange) {
      var components = weightedLanguageRange.replace(/\s+/, "").split(";")
      return {
        tag: components[0],
        quality: components[1] ? parseFloat(components[1].split("=")[1]) : 1.0,
      }
    })
    .filter(function (languageTag) {
      if (!languageTag) {
        return false
      }
      if (!languageTag.tag) {
        return false
      }
      return languageTag
    })
}
```

**Comment by markdon** [comment] 2024-02-06 03:46
@Jacob-Roberts Thanks for mentioning this! I'd never heard of Unicode CLDR. A great option for selecting fallback language.
