### ISSUE TITLE
Interval plurals

### ISSUE THREAD

**Issue by silkentrance** [i18next/i18next#541] opened 2016-02-03 21:15 UTC
What was the rationale for chosing

```
{
  "key1_interval": "(1){one item};(2-7){a few items};(7-inf){a lot of items};",
}
```

over

```
{
  "key1_1": "one item",
  "key1_2-7":"a few items",
  "key1_7-inf":"a lot of items"
}
```

I find the latter alternative much easier to read and author/maintain, especially with longer text.

Could this please be changed?

**Comment by jamuhl** [comment] 2016-02-04 08:37
The point is choosen solution is much easier and more performant. While i agree your suggestion is more clean to read.

The problem is i need to know all keys to decide which translation i have to choose. But we don't know keys upfront - so we would need to go through all existing keys and parse them to know if it belongs to requested key and if it defines an interval.

right now all the information is provided in one key and we could solve the complete interval selection inside a simple postProcessor - not adding to core size in cases where interval plural is not needed.

Considering interval plurals to be more of an edge case...i think current solution is acceptable. But still open for a PR.

**Comment by silkentrance** [comment] 2016-02-04 12:34
Then, and since this is JSON, how about

```
{
'key1_interval': {
   '0': ...,
   '1': ...,
   '2-7': ...,
   '7-inf': ...
}
}
```

Also much easier to read and maintain and also very easy to process.

**Comment by jamuhl** [comment] 2016-02-04 12:38
looks ok...will see what i can do.

**Comment by silkentrance** [comment] 2016-02-04 12:38
And, upon further consideration, existing plurals and intervals are pretty much alike in that

``
key1_1  ::= key1_interval_1
key1_2 ::= key1_interval_2-7
key1_7 ::= key1_interval_7-inf
key1_plural ::= key1_interval_7-inf
``

The sole difference being that ``key1_plural`` would also apply to ``0`` while ``key1_interval_7-inf`` might not.

**Comment by jamuhl** [comment] 2016-02-04 18:19
just checked if it's possible to have: 

```
'key1_interval': {
   '0': ...,
   '1': ...,
   '2-7': ...,
   '7-inf': ...
}
```

won't work:
- accessing i18next.t('key1_interval') will result in warning as result is object not a string (translation)
- changing to allow object (returnObjects = true) will result in applying postProcessor per member but not on the object of 'key1_interval' as postProcessors only work on string results.

further you suggestion would mean:
a) creating a new json format
b) lookup multiple keys to find plural and allow both formats: key1_7 and key1.7 (wouldn't hurt to much)

Not sure if i like the idea of supporting multiple formats just to have some nicer concept for interval plurals (which are used rarely).

**Comment by silkentrance** [comment] 2016-02-04 19:14
@jamuhl given the external representation, this could easily be translated to an internal representation, e.g.

```
'key1_interval': {
   '0': ...,
   '1': ...,
   '2-7': ...,
   '7-inf': ...
}
```

would be translated to

```
`key1_interval`: `{...}`
```

upon adding the resource to the resource store. That way, only the external representation needs to be adjusted and internally everything will work as is.

**Comment by jamuhl** [comment] 2016-02-05 08:33
assuming your loading the xhr backend you can override the parse function: https://github.com/i18next/i18next-xhr-backend#backend-options for doing this conversation.

**Comment by jamuhl** [comment] 2016-02-05 08:36
you might provide that parser...and we add that to i18next documentation as alternative 'cleaner' json format. On backends not yet having a parsing override i could add that.

**Comment by jamuhl** [comment] 2016-02-20 08:10
closing for now...feel free to reopen this

**Closed by jamuhl** 2016-02-20 08:10 UTC
Labels: feature request, V2
