### ISSUE TITLE
improve docs

### ISSUE THREAD

**Issue by vonovak** [i18next/i18next#913] opened 2017-04-25 10:55 UTC
For a newcomer, the docs feel incomplete, especially the API page.

[http://i18next.com/docs/api/#create-instance](http://i18next.com/docs/api/#create-instance) - what does that function do? Why would I want to use it? What is the difference between this and the `init` function? What are the params?

[http://i18next.com/docs/api/#init](http://i18next.com/docs/api/#init) reads: 

> Initializes the i18next instance.

Is it *the* instance? Or *an* instance?

**Comment by jamuhl** [comment] 2017-04-25 11:19
create instance - might be needed if you have a more complex setup (was requested by users) - the params are stated in the title "createInstance i18next.createInstance(options, callback)"

what you will mostly use is the init call on the instance that gets exported by default.

I agree the documentation could be a lot bigger and have more information. Would be more than happy to accept pull requests improving that: https://github.com/i18next/i18next.com

**Comment by vonovak** [comment] 2017-04-25 11:48
@jamuhl thanks! When I asked about the params, I meant what exactly is in those params.? What is the `option` object, what does the `callback` receive..? I will probably need multiple instances of the i18next object. Can you please expand on the difference between `createInstance` and `init`?

I would love to help improve the docs, but since I don't know how the lib works, I can't do that without digging a lot around the source code... Would be great if the docs were created together with the implementation.

**Comment by jamuhl** [comment] 2017-04-25 11:54
options are "documented" here: http://i18next.com/docs/options/#init-options
callback is the same as on calling init: function(err, t) {};

require('i18next') -> returns an instance without configuration -> so you need to call init with the options needed:

createInstance returns a new instance completely independent of the initial one return (has own storage, own language set,...) - createInstance with all options or call init afterwards:

`i18next.createInstance(options, () => {)` is the same as `i18next.createInstance().init(options, () =>
 {})`

**Comment by jamuhl** [comment] 2017-04-25 11:55
honestly myself i yet had no case where i needed multiple instances of i18next (beside testing)

**Comment by vonovak** [comment] 2017-04-25 12:04
Can I ask a question? if I write js module `A` like this:

```
import i18next from "i18next";

i18next.init(
  {
    lng: "en",
    resources: {
      en: {
        translation: {
          aaaa: "aaaa",
        }
      }
    }
  },
  (err, t) => {
    // initialized and ready to go!
  }
);

export default i18next;
```

and THEN module `B`

```
import i18next from "i18next";

i18next.init(
  {
    lng: "en",
    resources: {
      en: {
        translation: {
          bbbb: "bbbb",
        }
      }
    }
  },
  (err, t) => {
    // initialized and ready to go!
  }
);

export default i18next;
```

And then import from A and from B (say `import I18nA from A` and `import I18nB from B`) is the translation function going to have access to values defined in A or only in B? If the values introduced in A are rewritten by those from B, then I need multiple instances, right? My use case is a react-native app, so my plan is to have separate translation files for all component. I'm not limited by network connectivity so I hope this should work. Also hopefully there isn't too much overhead creating the instances.

**Comment by jamuhl** [comment] 2017-04-25 12:09
hm...you're right in B will overwrite A as the same instance is used.

But honestly i would (if the components don't be in separated modules) organise it in namespaces: http://i18next.com/translate/namespace/

and even use: https://github.com/i18next/react-i18next (we use that with react-native too)

**Comment by jamuhl** [comment] 2017-04-25 13:24
Maybe you might add some contribution to the documentation later - when you integrated i18next to your react-native project?

**Comment by vonovak** [comment] 2017-04-26 13:23
I'm currently evaluating which solution I'd like to go with... If I use i18next then yes :)

**Comment by jamuhl** [comment] 2017-04-26 13:32
fair enough ;)

**Comment by KINGMJ** [comment] 2017-04-28 07:22
sincerely,the docs is so difficult to understand

**Comment by jamuhl** [comment] 2017-04-28 07:31
@KINGMJ agree with you that one can improve that. But just saying the docs are difficult to understand does not help a lot.

Can you add some more info - what is/was hard to understand. Make suggestions to improve...

**Comment by pavlelekic** [comment] 2017-05-11 14:17
I have the same use case as @vonovak, I have a component library (React) that is distributed independently from the application, and I need translation to be encapsulated within the component library, and also to have translation inside the application that will not be clobbered by calling init twice on a global object. So I think the solution is to create two instances, one for component library and the other for the actual application that uses that component library.

Just to be sure, I can provide translations in the 'resource' field?
```
resources: {
      en: {
        translation: {
          aaaa: "aaaa",
        }
      }
    }
```

**Comment by jamuhl** [comment] 2017-05-11 15:01
@pavlelekic sure you can do that...or use http://i18next.com/docs/api/#add-resource-bundle

what we did on our projects was to pass down a t function to the library using a provider feed by a t function and consumed that t function with a own hoc. So that t function could be forwarded to components using it. As we did not want to configure loading via xhr and all the other options twice.

**Comment by Silviu-Marian** [comment] 2017-05-12 07:57
Just wanted to share our use case with `createInstance()`

We're using i18next at [Megalytic](https://megalytic.com) for translations in reports. The UI is supposed to stay English while the report contents can be in any other language

If we would later add the ability to change UI languages, the UI language will still be different from the reports language, and `createInstance()` would be the way to go :)

**Comment by jamuhl** [comment] 2017-05-12 08:19
@Silviu-Marian thanks for sharing....if using same translation files http://i18next.com/docs/api/#clone-instance might be the easier option...no extra loading, init - just use same store and be free to change language.

or use `const en = i18next.getFixedT('en');` to have a t function bound to `en` language

Funny how many options there are to get the same end result ;)

**Comment by corysimmons** [comment] 2017-05-19 02:44
I could be wrong, and I really appreciate all your work on this, but I think people are asking for something that reads like more of a story than a computer spitting out function names and keywords.

See Evan You's https://vuejs.org/v2/guide for a good example of what I mean.

I know you're busy so no worries if you can't/don't-want-to redo it now.

**Comment by jamuhl** [comment] 2017-05-19 06:32
@corysimmons thank you for pointing to that. It's a mix of not having time and writing great documentation needs a lot of skills i honestly lack which i lack (not an excuse). Will for sure work on this...but until than any PR on https://github.com/i18next/i18next.com would be awesome.

**Comment by corysimmons** [comment] 2017-05-19 17:32
Yeah I feel ya. If I end up using i18next I'll contrib, but docs might be _the reason_ I use react-intl instead tbh. :'(

**Comment by vonovak** [comment] 2017-05-19 20:47
@corysimmons that was my feeling as well

**Comment by jamuhl** [comment] 2017-05-20 07:03
So to get concreter on this ... you like to have a deeper introduction ... that shows deeper the benefits of using i18next...right?

Than more informations on every config option and API function.

Are at least the t function samples ok (they run actual i18next code)...might make them more interactive so you could change input/output?!? eg: http://i18next.com/translate/interpolation/ (not sure if people get the full config options on bottom, inkl. console.debug output,...)?!?

**Comment by jamuhl** [comment] 2017-05-20 07:12
Could you articulate what is better in https://github.com/yahoo/react-intl/wiki/API documentation...idk...but i don't get why that should be superiour? First time i tried out react-intl i dind not event get how to translate the website...just how to format dates and numbers using the intl API...idk might be i'm to stupid for getting that on the first run...

**Comment by jamuhl** [comment] 2017-05-20 09:50
Well anyway...worked on getting codeclimate setup and raised text coverage...so good next step might be a new documentation...

anyone nows a good sitegenerator that would parse from eg. github wiki pages - or any other suggestions? currently we use gatsby: https://github.com/gatsbyjs/gatsby --> mostly for having those translation samples

**Comment by corysimmons** [comment] 2017-05-20 14:04
How about GitBook?

**Comment by jamuhl** [comment] 2017-05-20 15:11
@corysimmons great hint...trying that out now...

**Comment by jamuhl** [comment] 2017-05-20 17:38
@corysimmons looks like the direction we should go: started playing around (adding jsfiddle for some samples, anchors, ...).

https://i18next.gitbooks.io/i18next/loading-translations.html

**Comment by jamuhl** [comment] 2017-05-20 17:39
if someone likes to contribute there - still 4 contributors i could invite

**Comment by corysimmons** [comment] 2017-05-20 21:51
So much better. Good job. Your work ethic alone makes me want to use i18next. 👏

**Comment by jamuhl** [comment] 2017-05-21 08:45
@corysimmons really works rather well - for sure there is a lot room for improvement still - but i believe contributing to docs get a lot simpler this way.

new pages:
https://i18next.gitbooks.io/i18next/content/getting-started.html
https://i18next.gitbooks.io/i18next/content/principles/namespaces.html
https://i18next.gitbooks.io/i18next/content/principles/fallback.html

**Comment by jamuhl** [comment] 2017-05-21 12:18
update:

https://i18next.gitbooks.io/i18next/content/interpolation.html
https://i18next.gitbooks.io/i18next/content/plurals.html

**Comment by jamuhl** [comment] 2017-05-24 09:54
@corysimmons @vonovak @KINGMJ @pavlelekic @Silviu-Marian worked hard on redoing documentations...there are still areas i will improve today or the next days (like the configuration options).

The new gitbook based documentation is now online http://i18next.com - so feedback or PRs on that would be very welcome.

**Comment by jamuhl** [comment] 2017-05-24 12:31
closing this for now...feel free to reopen if still totally unhappy with docs.

**Closed by jamuhl** 2017-05-24 12:31 UTC
Labels: doc, help wanted

**Comment by jamuhl** [comment] 2017-05-30 20:09
just to follow up...done an update to react-i18next documentations too: http://react.i18next.com

**Comment by Silviu-Marian** [comment] 2017-05-30 20:23
Great work. Not sure if fixable easily but the one thing I don't really like is how the samples climb up above the title. The reading order is confusing.

I'm not very familiar with GitBook either. Is this something we can fix?

**Comment by jamuhl** [comment] 2017-05-30 20:25
thats gitbook api default...you can toggle that with the button right hand of edit (on top)

**Comment by jamuhl** [comment] 2017-05-30 20:26
plus i could move the titles outside the sample code - that would make it look nicer

will do so when having time

**Comment by jamuhl** [comment] 2017-05-31 05:56
@Silviu-Marian https://www.i18next.com/api.html better like this...thanks for pointing to that visual problem

**Comment by corysimmons** [comment] 2017-05-31 10:23
If we're nitpicking, the logo should be an svg. Looks blurry on retina. 😅

**Comment by jamuhl** [comment] 2017-05-31 10:50
@corysimmons updated with svg. ;)

**Comment by corysimmons** [comment] 2017-05-31 15:04
Awesome, looks great.

Do you happen to know why this header underlaps? When I type in i18next.com I see

![image](https://cloud.githubusercontent.com/assets/224636/26638614/89dfdf9c-45f0-11e7-9447-4f261ba29719.png)

I don't have this issue on other GitBook sites:

![image](https://cloud.githubusercontent.com/assets/224636/26638665/a72cb066-45f0-11e7-9cdb-b4a592b8f4bf.png)

Did you manually modify some padding/margin around that?

Looks fine on Firefox.

Also getting a few https errors:

![image](https://cloud.githubusercontent.com/assets/224636/26638730/df440b70-45f0-11e7-9e56-f0b75b09bd7d.png)

**Comment by jamuhl** [comment] 2017-05-31 15:09
seems to be caused by the badges...let me try something

**Comment by jamuhl** [comment] 2017-05-31 15:16
nope...no idea...will have to look into this tomorrow

**Comment by corysimmons** [comment] 2017-05-31 15:44
Okay, not a big deal, just trying to polish it up a bit.

It's amazing what nice docs can do. I'm genuinely excited about using this now. :\

**Comment by jamuhl** [comment] 2017-05-31 15:45
really strange...only first render does that...going to another page and back does fix it...

will need to have a look again tomorrow...out now

**Comment by jamuhl** [comment] 2017-06-01 07:28
@corysimmons should be fixed now...had to do some layout changes...weird behaviour...seems some script did some scroll on load.

**Comment by corysimmons** [comment] 2017-06-01 15:05
Nice. Weird.

I opened an issue with packagequality.com on migrating from http to https to clean up the console.

All out of nitpicks until I dig into the docs, but your work ethic is enough to make me really interested in this project. Kudos and thank you! 👏

**Comment by ManelGonzalez-ops** [comment] 2020-08-08 17:49
why this isn't woroking?
import React, { Suspense } from 'react';
import { useTranslation } from 'react-i18next';

function Page() {
  const { t, i18n } = useTranslation();

  const changeLanguage = lng => {
    i18n.changeLanguage(lng);
  };

  return (
    <div className="App">
      <div className="App-header">
        <button onClick={() => changeLanguage('de')}>de</button>
        <button onClick={() => changeLanguage('en')}>en</button>
      </div>
      <div>{t('test')}</div>
    </div>
  );
}

export default function App() {
  return (
    <Suspense fallback={<div>loading...</div>}>
      <Page />
    </Suspense>
  );
}
Why isn't this even working ?
I think you should spend some more time writting the docs, or at least not splitting them up in different sections as if they were optional, at least with react-i18next docs.

**Comment by jamuhl** [comment] 2020-08-08 20:21
@ManelGonzalez-ops if there is an issue - please open one - and please be a little more specific in what does not work...regarding the docs...feel free to contribute to them...help to make OSS great again...
