### ISSUE TITLE
Typing error / autocompletion with `useTranslation` and `t` hook

### ISSUE THREAD

**Issue by viclafouch** [i18next/i18next#1969] opened 2023-06-06 09:56 UTC
## 🐛 Bug Report

I cloned the repository https://github.com/i18next/next-i18next for testing the `example/simple` project and I found the same typing error in my project.

```ts
{t('common:blog.optimized.question')} // Typing error
```
but
```ts
{t('blog.optimized.question')} // working
```
is working

Normally, both cases are working because `common` is indicate as the defaultNamespace in the TS declaration file.

### Other typing issue

When using the `useTranslation` function, I only have `common` for autocompletion, I don't have the others namespaces.. 

## To Reproduce

* Clone the repo https://github.com/i18next/next-i18next
* In the `index.tsx` page, replace `{t('blog.optimized.question')}` by `{t('common:blog.optimized.question')}`
<img width="768" alt="image" src="https://github.com/i18next/i18next/assets/23353836/4b499972-9cfc-4e95-ad2d-00670f7bc83c">

And for the second typing issue

* Use the `useTranslation` hook, autocompletion will give you `common` only, not `footer`and `second-page`.

<img width="781" alt="image" src="https://github.com/i18next/i18next/assets/23353836/f686f678-e7da-45d4-a90e-8687db970783">

## Expected behavior

Typing would work for both cases

## Your Environment

- *runtime version*: node 16
- *i18next version*: latest
- *os*: Mac

**Comment by adrai** [comment] 2023-06-06 10:01
Can you try with the upcoming ts changes: https://github.com/i18next/i18next/pull/1911 ?

**Comment by adrai** [comment] 2023-06-15 09:47
Please try with i18next v23.0.1 and react-i18next v13.0.0

**Comment by viclafouch** [comment] 2023-06-15 17:58
Let me check thanks ;)

**Comment by viclafouch** [comment] 2023-06-19 10:26
Nah it doesn't work even with the last version, `t('common:hello')` is not accepted, only `t('hello')`

**Comment by viclafouch** [comment] 2023-06-19 10:39
yes but in our company, don't want to pass any NS to the hook, we prefer to include it inside the t `fn`. So for now, we still doesn't use the TypeScript globals until it works :/

**Comment by adrai** [comment] 2023-06-19 10:44
fyi: the preferred way is to pass the namespace via options, and not via prefix: https://react.i18next.com/guides/multiple-translation-files

```js
i18next.t('common:look.deep'); // not recommended with ns prefix when used in combination with natural language keys
// better use the ns option:
i18next.t('look.deep', { ns: 'common' })
```

**Comment by joleb** [comment] 2023-06-19 10:49
@adrai we are correctly using namespaces and i also tried using the "ns" property, sadly i still get the same error:
![image](https://github.com/i18next/i18next/assets/38313415/b1e749eb-a308-421c-a135-16218198abbe)

**Comment by adrai** [comment] 2023-06-19 10:51
Seems to work here: https://github.com/i18next/next-i18next/blob/master/examples/simple/pages/index.tsx
<img width="554" alt="image" src="https://github.com/i18next/i18next/assets/1086194/f73e4e95-f6e3-4ef9-a736-eb04eaf9bea8">

@joleb please provide a minimal reproducible example repo

**Comment by joleb** [comment] 2023-06-19 12:29
> Seems to work here: https://github.com/i18next/next-i18next/blob/master/examples/simple/pages/index.tsx <img alt="image" width="554" src="https://user-images.githubusercontent.com/1086194/246808259-f73e4e95-f6e3-4ef9-a736-eb04eaf9bea8.png">
> 
> @joleb please provide a minimal reproducible example repo

working on it and it seems like a problem on my side. its just strange it appears after upgrading to the latest versions. thanks for the help so far, working on fixing it. 🚀

**Comment by joleb** [comment] 2023-06-19 13:07
our issue was caused by having `"strict":false` inside our .tsconfig, thanks for the help anyway @adrai , helped me to improve the typing on our project! 🥇

**Comment by pedrodurek** [comment] 2023-07-29 00:30
I'll close this task for now, feel free to reopen it if needed

**Closed by pedrodurek** 2023-07-29 00:30 UTC
Labels: typescript

**Comment by Darhagonable** [comment] 2023-11-03 22:34
@pedrodurek 
https://codesandbox.io/s/namespaceprefix-l29qf9?file=/src/App.tsx
Typescript complains even though it's actually working.
