### ISSUE TITLE
defaultNS with Typescript

### ISSUE THREAD

**Issue by yuri-lomashko-itechart** [i18next/i18next#1855] opened 2022-10-24 10:49 UTC
## 🐛 Bug Report

It seems that `i18next` doesn't respect type of defaultNS in .d.ts file while using `t` function

## To Reproduce

Code example:

#### i18next.d.ts
```ts
import { resources, defaultNS } from '../src/i18next';

declare module 'i18next' {
    interface CustomTypeOptions {
        defaultNS: typeof defaultNS;
        resources: typeof resources['en'];
    }
}
```
#### i18next.ts
```ts
import en from './translations/en.json';

export const defaultNS = 'general';

export const resources = {
    en: {
        general: en,
    },
} as const;

i18n.use(initReactI18next)
    .init({
        resources,
        fallbackLng: 'en',
        ns: ['general'],
        defaultNS,
        compatibilityJSON: 'v3',
        interpolation: {
            escapeValue: false,
            skipOnVariables: false,
        },
        react: {
            useSuspense: false,
        },
    });
```
#### Use cases
```ts
// i18next
i18next.t('common.errors.required') // typescript error
i18next.t('general:common.errors.required') // valid

// react-i18next
const { t } = useTranslation();
t('common.errors.required'); // valid
```

## Expected behavior

```ts
// i18next
i18next.t('common.errors.required') // valid
i18next.t('general:common.errors.required') // valid
```

## Your Environment

- *runtime version*: react-native 0.70.3
- *i18next version*: 12.0.0
- *react-i18next version*: 22.0.2
- *os*: Mac
- *typescript*: 4.8.4

**Comment by pedrodurek** [comment] 2022-10-24 16:58
Thanks @yuri-lomashko-itechart!
I noticed that his weekend, I'll put a PR up to fix that

**Comment by daveallie** [comment] 2022-10-26 01:11
I suspect it's just this line here: https://github.com/i18next/i18next/blob/96613faccfea2cbf95de8ffce12119611af65e00/index.d.ts#L1133

It should read: `t: TFunction;` instead of `t: TFunction<FallbackOrNS<string>[]>;` right?

**Comment by pedrodurek** [comment] 2022-10-27 17:31
@daveallie It's not that simple, `t: TFunction` will set the namespace with the default namespace, which means you'll only have access to keys from the default namespace.

**Comment by daveallie** [comment] 2022-10-27 22:41
oh interesting, good point.

How about something like this:

```ts
const resources = {
  en: {
    general: {
      common: {
        errors: {
          required: 'foo',
        },
      },
    },
    otherKey: {
      other: {
        value: 'bar',
      },
    },
  },
} as const;

i18n.use(initReactI18next).init({
  // ...
  defaultNS: 'general',
  resources,
});
```

```ts
type TFunctionInferredNS = Namespace extends infer N
  ? N extends FallbackOrNS<never>[]
    ? TFunction<N | DefaultNamespace>
    : never
  : TFunction<DefaultNamespace>;

// ...
  t: TFunctionInferredNS;
// ...
```

```ts
i18next.t('common.errors.required'); // valid
i18next.t('general:common.errors.required'); // valid
i18next.t('otherKey:other.key'); // valid
i18next.t('other.key'); // invalid
```

I'm sure that type could be crafted a bit better, I am by no means a typescript savant

**Comment by daveallie** [comment] 2022-10-27 22:58
Wait, I am being dumb, that type doesn't actually do much, it could just be:

```ts
t: TFunction<Namespace | DefaultNamespace>;
```

🤦‍♂️ don't mind me

**Comment by kabomi** [comment] 2022-11-09 13:17
Hi,

any progress here?

it would be great if we could avoid to write the default ns every time. Thanks

**Comment by sven-meyer-wetter-com** [comment] 2022-11-10 10:22
I noticed this too. A fix for this would be great!

**Comment by itsramiel** [comment] 2022-11-10 14:10
encountered this while upgrading

**Comment by daveallie** [comment] 2022-11-11 08:01
For those looking for a short-term fix while an official change is made, you can use the above change I mentioned along with `patch-package` to resolve the type errors.

Steps:
1. Install `patch-package`: Details [here](https://github.com/ds300/patch-package#set-up)
2. Open `node_modules/i18next/index.d.ts`
3.  Replace [this line](https://github.com/i18next/i18next/blob/26073c4ffb5ff5e98df0117c7930399de54c1bf6/index.d.ts#L1133) (`t: TFunction<FallbackOrNS<string>[]>;`) with `t: TFunction<Namespace | DefaultNamespace>;`
4. Save the file and run `yarn patch-package i18next`
    - This should create a new `patches/i18next+<version>.patch` file, make sure to commit this

That should resolve your type issues, once this package is updated and you update locally, you'll get a warning from patch-package and you'll be able to remove that patch file.

**Comment by kabomi** [comment] 2022-11-11 08:55
Hey @daveallie  didn't know about patch-package, I really appreciate your comment/solution.

**Comment by daveallie** [comment] 2022-11-22 22:55
This is still an issue, happy to the put a PR out for the suggested fix (changing the type of the global `t` export to be `TFunction<Namespace | DefaultNamespace>;`) if you'd like?

**Comment by oxc** [comment] 2022-11-22 23:27
That solution works nicely for us, so I think a PR for it should be very welcome.

**Comment by daveallie** [comment] 2022-11-22 23:52
Pull request created https://github.com/i18next/i18next/pull/1870

**Comment by adrai** [comment] 2022-12-05 22:02
@pedrodurek do you see any chance for having the `i18next.t('keyWithoutNsPrefix')` working when using the defaultNS option?
Like this is working?
```js
const myT = i18next.getFixedT('en')
myT('keyWithoutNsPrefix')
```

**Comment by flygomel** [comment] 2022-12-06 14:21
also invalid if:
const { t } = useTranslation('test');
t('anyNS:example'); // typescript error

**Comment by adrai** [comment] 2022-12-09 09:56
fyi: passing the ns via options should now work with v22.1.5
=> `i18next.t('foobar.barfoo', { ns: 'alternate' });`

**Comment by Yooooomi** [comment] 2022-12-09 09:59
Our workaround to this, allowing type to behave the way we want is this ugly type definition

```ts
declare module 'i18next' {
  // Extend CustomTypeOptions
  interface CustomTypeOptions {
    // hack to overcome bad typing
    // https://github.com/i18next/i18next/issues/1855
    keySeparator: '.';
    nsSeparator: '';
    defaultNS: '';
    resources: {
      '': typeof fr;
    };
    // other
  }
}
```

**Comment by adrai** [comment] 2022-12-09 10:03
> Our workaround to this, allowing type to behave the way we want is this ugly type definition
> 
> ```ts
> declare module 'i18next' {
>   // Extend CustomTypeOptions
>   interface CustomTypeOptions {
>     // hack to overcome bad typing
>     // https://github.com/i18next/i18next/issues/1855
>     keySeparator: '.';
>     nsSeparator: '';
>     defaultNS: '';
>     resources: {
>       '': typeof fr;
>     };
>     // other
>   }
> }
> ```

You should be able to just not define the resources property, then the resources key checks will not be done....

```ts
declare module 'i18next' {
  // Extend CustomTypeOptions
  interface CustomTypeOptions {
    // hack to overcome bad typing
    // https://github.com/i18next/i18next/issues/1855
    keySeparator: '.';
    nsSeparator: ':';
    defaultNS: 'translation';
    // resources: {
    //   '': typeof fr;
    // };
    // other
  }
}
```

**Comment by adrai** [comment] 2022-12-11 21:11
fyi: v22.4.1 brings a couple of defaultNS type fixes

**Comment by flygomel** [comment] 2022-12-12 08:34
in v22.4.2 this case does not work yet:

```
const { t } = useTranslation('anyNS');

t('otherNS:published')} // ts error
```

**Comment by adrai** [comment] 2022-12-12 08:39
> in v22.4.2 this case does not work yet:
> 
> ```
> const { t } = useTranslation('anyNS');
> 
> t('otherNS:published')} // ts error
> ```

try: 

```js
const { t } = useTranslation(['anyNS', 'otherNS'|);

t('otherNS:published')}
```

**Comment by yuri-lomashko-itechart** [comment] 2022-12-13 09:51
It seems like current problem was fixed, but interpolation types was broken, I'll create another ticket

**Comment by adrai** [comment] 2022-12-13 09:55
> It seems like current problem was fixed, but interpolation type was broken, I'll create another ticket

https://github.com/i18next/react-i18next/issues/1547 ?

**Comment by yuri-lomashko-itechart** [comment] 2022-12-13 10:14
Nope, For now it doesn't work at all on `i18next` level
```ts
i18next.t('common.errors.max_length_characters', { length: 500 }) // i18next doesn't work

t('common.errors.max_length_characters', { length: 500 }) // react-i18next works
```

**Comment by adrai** [comment] 2022-12-13 10:16
> Nope, For now it doesn't work at all on `i18next` level
> 
> ```ts
> i18next.t('common.errors.max_length_characters', { length: 500 }) // i18next, ts error
> 
> t('common.errors.max_length_characters', { length: 500 }) // react-i18next works
> ```

can you provide a test case here? https://github.com/i18next/i18next/blob/master/test/typescript/custom-types/t.test.ts

**Comment by adrai** [comment] 2022-12-13 10:21
@yuri-lomashko-itechart ahh I know what you mean....

**Comment by adrai** [comment] 2022-12-13 10:26
v22.4.5 should fix that

**Comment by adrai** [comment] 2022-12-13 10:32
So can this issue be closed?

**Comment by yuri-lomashko-itechart** [comment] 2022-12-13 10:33
yep, thanks!

**Closed** 2022-12-13 10:33 UTC
Labels: typescript

**Comment by Temez1** [comment] 2023-02-01 10:30
Not sure if related or should open a new issue:

Changing the namespace gives a typescript error:



```
// Default namespace "home"
setDefaultNamespace("news");

{t("some")}        // No overload matches this call.
{t("news:some")}   // Happy
```

**Comment by adrai** [comment] 2023-02-01 10:33
> Not sure if related or should open a new issue:
> 
> 
> 
> Changing the namespace gives a typescript error:
> 
> 
> 
> 
> 
> 
> 
> ```
> 
> // Default namespace "home"
> 
> setDefaultNamespace("news");
> 
> 
> 
> {t("some")}        // No overload matches this call.
> 
> {t("news:some")}   // Happy
> 
> ```
> 
>  

I don't know if this can be handled in TS... what do you think @pedrodurek?

**Comment by Temez1** [comment] 2023-02-01 10:47
Also, I had a bug related to default namespaces and using arrays & objects. [yassinedoghri/astro-i18next/issues/#117](https://github.com/yassinedoghri/astro-i18next/issues/117)

**Comment by pedrodurek** [comment] 2023-02-01 16:56
Yeah, it's not possible to update types in runtime. I'd suggest to use the more explicit approach:
```
const {t} = useTranslations('news');
{t("some")}   
// or
const {t} useTranslations(['news']);
{t("news:some")}
```

**Comment by adrai** [comment] 2023-12-13 14:35
@LaGregance please provide a reproducible example, not just a code snippet

**Comment by adrai** [comment] 2023-12-13 15:12
> I just realized that my problem comes from my typecript configuration `strictNullChecks: false`, I can't set this option to true because my current project gets thousands of errors with this option. I know the doc says this option is mandatory, but is there any way to work without it?
> 
> Thanks.

no, strict or strictNullChecks is required

**Comment by LaGregance** [comment] 2023-12-13 15:21
Ok, thanks for your time.
This isn't the right place to talk about it, but do you think it's relevant to start a discussion about making typecheck work with strictNullChecks? Because I think it could be a barrier to adoption for many projects that use this option.

**Comment by adrai** [comment] 2023-12-13 15:27
> Ok, thanks for your time.
> 
> This isn't the right place to talk about it, but do you think it's relevant to start a discussion about making typecheck work with strictNullChecks? Because I think it could be a barrier to adoption for many projects that use this option.

I don't think that will work, but feel free to try a PR

**Comment by diegods-ferreira** [comment] 2024-05-27 17:56
> Hi,
> 
> It's look like there is a regression on this issue on version 23+:
> 
> ```ts
> i18next.t('translation:myKey'); // Work
> i18next.t('myKey'); // Typescript error
> ```
> 
> Tested with i18next `23.7.9` & `23.7.9`, using Typescript 5.3.3
> 
> It's work fine on version 22.5.1 using same typescript version (but autocomplete of the `t` function is broken in intelliJ).

I'm facing the same issue.

- i18next: `23.11.5`
- typescript: `5.4.5`

I haven't find a solution yet.
