### ISSUE TITLE
Use local and backend translation together

### ISSUE THREAD

**Issue by 0FilipK** [i18next/i18next#1268] opened 2019-06-17 16:55 UTC
Hello, I'm using old v9 i18next version currently and I'm wondering is it possible to use both: local and backend translations together? I'm trying to provide local resources and backend options in init but it doesn't work.

What I want to achieve is load local version as soon as possible to prevent ugly white screen (when only backend is configured and react.wait: true) and untranslated text also. I imagine this like loading local, then download the newest translation file from backend and rerender all components.

Can be done in newer - V10 version maybe?

**Comment by jamuhl** [comment] 2019-06-17 17:05
closing as duplicate of https://github.com/i18next/react-i18next/issues/873

**Closed by jamuhl** 2019-06-17 17:05 UTC
