### ISSUE TITLE
Fallback for locale with script in it

### ISSUE THREAD

**Issue by dbendy** [i18next/i18next#805] opened 2016-07-27 19:41 UTC
Right now, if I have a locale such as `sr-Cyrl-BA`, when `i18next` does a translation lookup, if there are no translations available for that locale, it falls back to `en`, even if there are translations available for `sr-Cyrl`.  It should fallback to `sr-Cyrl` first, then `sr`, and then `en`.  (And maybe it should try `sr-BA` too ?)

**Comment by jamuhl** [comment] 2016-07-28 11:15
https://github.com/i18next/i18next/issues/748#issuecomment-227978416

will implement a more flexible option to define fallbacks for languages...but will take some time...on holiday right now

**Comment by arch0njw** [comment] 2016-10-05 20:10
I too need this level of functionality.  The literal lookup of nn-Ssss-RR when there are values in nn-Ssss can be a problem when supporting regionalized versions of that locale/script.

Also, if this kind of locale code parsing is sufficiently isolated within i18next, implementors could write their own methods to perform extensions.  There are other forms of falling back such as attempting to lookup a value in a zh-CN file when the locale code is zh-Hans -- or vice versa

**Comment by jamuhl** [comment] 2016-10-06 07:51
duplicate of https://github.com/i18next/i18next/issues/748

right mention there a PR would be welcome...right now i'm to busy working on our localization as a service offering http://locize.com . This will land sooner or later as i see the importance....but like said right now the time is limited to add such a feature.

**Closed by jamuhl** 2016-10-06 07:51 UTC

**Comment by arch0njw** [comment] 2016-10-06 11:37
Understood and thank you.
